### ISSUE TITLE
Checkstyle is not working

### ISSUE THREAD

**Issue by boredcoco** [nus-cs2103-AY2223S1/forum#114]
Checkstyle does not seem to be working as my gradle cannot build with the checkstyle plugin. 
<img width="1347" alt="Screen Shot 2022-08-31 at 6 12 45 PM" src="https://user-images.githubusercontent.com/75612806/187655782-93efc82c-d883-4a40-bccb-bc85db1de9c1.png">

I would appreciate any help given, thanks in advanced!

**Comment by RussellDash332** [comment]
Have you taken the xml files from the addressbook3 repository?

**Comment by sltsheryl** [comment]
I think a few things you can try is 
1. Ensure you have the checkstyle.xml and suppressions.xml files in a config folder in your project. They should be filled, the content copied from the address book.
2.  Check the tool version in the build.gradle file and the Checkstyle version that you set should be the same as that (for me it was initially different)
3. Remember to add the plugins in your build.gradle file (saw some people encountered this error on stack overflow because of this)

**Comment by jetlfj** [comment]
Consider checking this guide out if you are still having trouble: #35
