### ISSUE TITLE
gradlew commands failing 

### ISSUE THREAD

**Issue by ReubenChay** [nus-cs2103-AY2223S1/forum#116]
Hi! When I run any command using gradlew (tried clean/build/checkstyle/shadowJar) it all fails with this error: 

FAILURE: Build failed with an exception.
* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 764ms

I read through a previous thread with this exact same issue and tried the solutions but it still doesn't work. Any help would be appreciated!

Link to repo: https://github.com/ReubenChay/ip.git

**Comment by damithc** [comment]
While waiting for inputs from others, here are some things you can try:
* Push the code to a branch (or the master branch) and share here so that other can try to replicate the problem.
* If using Intellij, try these 'common remedies' one-at-a-time in this order:
  * File -> Invalidate caches
  * Delete the .idea folder -> Close and re import the project
  * Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.

**Comment by ReubenChay** [comment]
Thanks prof! Just added the link to my repo. I tried the above solutions one by one but I still get the same error

**Comment by xzzz3** [comment]
Hey Reuben! This issue might have been caused by incompatibility between gradle and JDK. 
I can see from your repo that you are using gradle 6.2, are you using a compatible Java version? From this [link](https://docs.gradle.org/current/userguide/compatibility.html), you should use Java 13 and below.

**Comment by damithc** [comment]
@ReubenChay which OS and which terminal are you using to run the Gradle commands? What do you see if you run the `java -version` command in that terminal?

**Comment by ReubenChay** [comment]
@xzzz3 Hi! Yea I am using java 11 for IntelliJ. 
@damithc Hi prof, I'm using my CLI on mac os. My machine java version is 16.

Could this be the issue? If i use CLI to run it will it use java 16 instead? If so, how can I force it to use 11 instead?

**Comment by damithc** [comment]
> Could this be the issue? If i use CLI to run it will it use java 16 instead? If so, how can I force it to use 11 instead?

@ReubenChay You can find out which version is used by the CLI if you run the `java -version` command in the same terminal you are running Gradle commands.

Let's wait to see if other Mac users can share how to change the Java version used in the terminal. You can also try to Google for it in the meantime.

**Comment by leonidas1712** [comment]
For changing the java version from the terminal on Mac, try taking a look at this [link](https://stackoverflow.com/questions/21964709/how-to-set-or-change-the-default-java-jdk-version-on-macos).

Do take a look at the [advisory](https://nus-cs2103-ay2223s1.github.io/website/admin/programmingLanguages.html) on downloading the correct JDK 11 version for Mac if you still run into issues!

**Comment by ReubenChay** [comment]
@huzaifa1712 @damithc  thank you for the help! Managed to work on both my cli and gradle tools on intellij now.
