### ISSUE TITLE
IP progress dashboard updates

### ISSUE THREAD

**Issue by onepersonhere** [nus-cs2103-AY2223S1/forum#136]
I have completed the task "Use GFMD", may I know when will the dashboard be updated?

**Comment by sikai00** [comment]
According to the [progress dashboard description](https://nus-cs2103-ay2223s1.github.io/dashboards/contents/ip-progress.html), the dashboard should be updated in a script run that occurs once per day.  
For today,  
<img width="506" alt="image" src="https://user-images.githubusercontent.com/63795894/188256979-4b23608d-19fa-48e2-af7b-c45efabe31fb.png">    
script was ran at 1039. So you probably have to wait for tomorrow for the next script run.

**Comment by onepersonhere** [comment]
Thanks @sikai00 , may I know if there are penalty for late submission?

**Comment by sikai00** [comment]
Here's a [page](https://nus-cs2103-ay2223s1.github.io/website/admin/weeklySchedule.html#deadline-for-weekly-tasks  ) from the admin info where you can look up more information if you need.
I believe there shouldn't be any since the GFMD hard deadline was just yesterday.  

<img width="823" alt="image" src="https://user-images.githubusercontent.com/63795894/188257253-95e7695b-8a36-48d4-8b4a-4df02664f7f6.png">

**Comment by damithc** [comment]
> Here's a [page](https://nus-cs2103-ay2223s1.github.io/website/admin/weeklySchedule.html#deadline-for-weekly-tasks) from the admin info where you can look up more information if you need.
> I believe there shouldn't be any since the GFMD hard deadline was just yesterday.

@sikai00 is correct. There will be no penalty if you catch up within a few days.

**Comment by onepersonhere** [comment]
Thanks!
