### ISSUE TITLE
help with setting up codecov

### ISSUE THREAD

**Issue by izzahaj** [nus-cs2103-AY2223S1/forum#147]
I followed the DevOps [guide](https://nus-cs2103-ay2223s1.github.io/tp/DevOps.html) given to set up codecov for the tp repo but so far all the CI runs shown in GitHub actions have failed after pushing dummy commits:
<img width="1292" alt="Screenshot 2022-09-05 at 8 47 46 PM" src="https://user-images.githubusercontent.com/88933129/188453605-8f5a2f17-ba71-48d7-b8d9-9d6b858c0fbc.png">

On the Codecov website, it says that my tp repo has not been set up yet despite following the instructions given in both the DevOps guide and [here](https://app.codecov.io/gh/AY2223S1-CS2103T-T12-4/tp/new).

Any help would be greatly appreciated!

**Comment by damithc** [comment]
@izzahaj Note that it takes some time for CodeCov to recognize that you have given it permission to push to your repo. You can try again in a few hours and post here if it still doesn't work.

**Comment by RussellDash332** [comment]
@izzahaj Looking at [this page](https://github.com/AY2223S1-CS2103T-T12-4/tp/runs/8188649343?check_suite_focus=true), the issue is just checkstyle. You simply need to add a newline at the EOF of Main.java.
```
Run ./run-checks.sh
  ./run-checks.sh
  shell: /usr/bin/bash -e {0}
ERROR:../src/main/java/seedu/address/Main.java:[2](https://github.com/AY2223S1-CS2103T-T12-4/tp/runs/8188649343?check_suite_focus=true#step:5:2)6: no newline at EOF.
Error: Process completed with exit code 1.
```

Note that you can commit without doing any modifications at all, you can see how Prof did the same thing at [the iP dashboard](https://github.com/nus-cs2103-AY2223S1/ip-dashboard)
```sh
git commit --allow-empty
```

**Comment by izzahaj** [comment]
Thank you for the replies! @RussellDash332 I've added a newline and it works now.
