### ISSUE TITLE
Very odd commits reflected in version history

### ISSUE THREAD

**Issue by Darren12345677** [nus-cs2103-AY2223S1/forum#148]
![image](https://user-images.githubusercontent.com/63776243/188636834-b569d158-de34-41d1-ad65-39821f401686.png)

Hi friends, I have 2 commits labeled "Merge branch 'master' of https://github.com/Darren12345677/ip" after I merged 2 pull requests from 2 branches and I do not know what that commit is or how it came about. Why is there no destination branch?

**Comment by leonidas1712** [comment]
Perhaps it was because some changes were made to your master branch (through the pull requests you merged?) and when you tried to update your master branch locally git suggested to pull the changes because of divergent histories, making these 'weird' merge commits.

Seems similar to the behaviour described [here](https://gist.github.com/joallard/6518431) and [here](https://stackoverflow.com/questions/7120199/github-merge-branch-master).

**Comment by Darren12345677** [comment]
Thank you so much! @huzaifa1712 
The links were very helpful. I realized that when I pull from remote Master to local Master, I tick the option to "Create a new merge commit even if fast-forward is possible" which created that merge commit message. This is unnecessary because I already merged the branch via pull request and I am only pulling the remote Master to update my local repository.
