### ISSUE TITLE
'javac' is not recognized error while running text-ui-test

### ISSUE THREAD

**Issue by april-anh** [nus-cs2103-AY2223S1/forum#15]
I'm using Windows and when I try to run the ```runtest.bat``` file in the ```text-ui-test``` folder I get the following error message.

```
cmd.exe /c runtest.bat
********** BUILD FAILURE ************
'javac' is not recognized as an internal or external command,
operable program or batch file.

```

**Comment by leonidas1712** [comment]
Just in case you haven't seen it: does this link help?
As teoyuqi says, if Java was installed correctly it may be an issue with your PATH variable.

https://stackoverflow.com/questions/7709041/javac-is-not-recognized-as-an-internal-or-external-command-operable-program-or

**Comment by teoyuqi** [comment]
I encountered this issue as well, and it turned out that ```javac``` wasn't added to ```Path``` *(i.e. your computer doesn't know where to find the ```javac``` command)*

You can set up your Path using the steps shown [here](https://www.delftstack.com/howto/java/add-javac-to-windows-path/).

Oh and remember to **restart Intellij afterwards**. :)

**Comment by april-anh** [comment]
Thanks @teoyuqi and @huzaifa1712 ! The problem is solved.
