### ISSUE TITLE
Access is denied error when running batch file

### ISSUE THREAD

**Issue by guowei42** [nus-cs2103-AY2223S1/forum#16]
Currently on windows using WSL for the iP project. When I try to run the batch file, I get the following error. It was working a moment ago though, not sure what I did that caused this now.

```
Access is denied
<path to ACTUAL.TXT>
Access is denied
FC: cannot open ACTUAL.TXT - No such file or folder
```

**Comment by Eclipse-Dominator** [comment]
Hello, if you are using wsl, you should be running the `runtest.sh` file instead of the `runtest.bat` file. 
Are you coding in wsl environment but executing the `runtest.bat` file in windows?

**Comment by RussellDash332** [comment]
You can change the permission of the file (that should be allowed for now?)
```sh
$ chmod 744 runtest.sh
```

**Comment by Eclipse-Dominator** [comment]
Actually, I realised FC is file compare on windows. So you are definitely running the bat file.
I have a friend who had similar problems, the sudden denial of access could be due to anti-virus blocking access permissions of the batch file. So you can disable your anti-virus temporarily to see if it resolves the permissions issue.

Once again, if you are using a linux environment for the iP project, I would recommend doing the testing using the provided `runtest.sh` file. It might not run as the original file contains carriage returns `\r`. But if you encounter that, you can install `dos2unix` from apt or whatever package manager your WSL system is using and pass the file through `dos2unix` to remove the carriage return (`dos2unix runtest.sh runtest.sh`).

**Comment by lyuting47** [comment]
Hi you can try right clicking the batch file and run as administrator. I also got the access is denied error when I tried to run it in command prompt window.

**Comment by guowei42** [comment]
Thanks for the help everyone! Yeah, using wsl and was running the `runtest.bat` file, needed to run the `runtest.sh` file instead. Also needed to do a `$ chmod 744 runtest.sh` and installing `dos2unix`.
