### ISSUE TITLE
Unable to read inputs from duke.txt

### ISSUE THREAD

**Issue by PokezardVGC** [nus-cs2103-AY2223S1/forum#178]
Hi guys, I might need help to understand why I am not reading any files from my duke.txt files. even though there was a previosu log. Was working normally before abstracting it via OOP so not sure what happen. Currently in debugging mode as shown in the images. (extracted the boolean hasNextLine out to illisturate this, original code runs sc.hasNextLine() normally)

Used the exact same file path for both read and write so kinda puzzling why read is not detecting but write is

![image](https://user-images.githubusercontent.com/71965541/189622778-62579226-1e1e-4611-b696-9fbfa855de81.png)
![image](https://user-images.githubusercontent.com/71965541/189622805-03984af4-46d8-46a0-a147-6b26fd1c7168.png)

Would greatly appreciate if anoyone has encountered a similar problem. 

Github link: https://github.com/PokezardVGC/ip

**Comment by damithc** [comment]
@PokezardVGC Confirmed your problematic code is already in your fork? Asking because your latest commit in your fork https://github.com/PokezardVGC/ip/commits/master was done 4 days ago.

**Comment by deeyonn** [comment]
I suspect its caused by closing myReader at the end of the function?

i.e., 
1. When you initialise your Storage object, it creates an instance of Scanner myReader and opens it, that's great.
2. When you run your readDuke function once, perhaps it works because myReader is still open.
3. At the end of the first readDuke run, myReader is closed.
4. Subsequent calls to readDuke might be using an instance of myReader that is already closed.

Perhaps you can push to a branch and post the branch here with steps stating intended outcome and actual outcome?

Edit1: I also noticed that you are using absolute file paths in your Storage class. I believe the weekly tasks recommend you to explore using relative file paths which can easily be done using `String userHome = System.getProperty("user.home");`

**Comment by PokezardVGC** [comment]
Hi prof, I've actually encountered this problem since then but wanted to try it out before asking on forum gor help. Pushed my latest commits to the fork in master

**Comment by PokezardVGC** [comment]
@deeyonn , I've only ran readDuke once though so I am not too sure if  closing at the end of the method would affect? Am I getting your point correctly? Currently readDuke is unable to read anything from duke.txt (myReader.hasNextLine() == false). Appreciate your though to help though

**Comment by deeyonn** [comment]
@PokezardVGC You can try to troubleshoot by reducing the scope to the readDuke function.

i.e., Pull File and Scanner into readDuke as local variables and initialise them every function run, then closing them at the end of the run.

**Comment by PokezardVGC** [comment]
@deeyonn , I've followed your recommendation of putting the scanners in the readDuke method. I've loaded 2 test lines in duke.txt for reference. It still says there is no nextLIne in duke.txt when there are inputs

Branch in: https://github.com/PokezardVGC/ip/tree/readDuke_not_working

**Comment by nehcuy** [comment]
Instead of doing:
```java
while (myReader.hasNextLine()) {
...
}
```
on line 48 of your `Storage` class,

Try doing:
```java
String userInput = myReader.nextLine();
while (true) {
    ... 
    // Switch statements go here
    if (!myReader.hasNextLine()) {
        break;
    }
    userInput = sc.nextLine();
}
```

[Here](https://github.com/nehcuy/ip/blob/master/src/main/java/duke/storage/Storage.java) is my `Storage` class for reference :>

**Comment by PokezardVGC** [comment]
Hi guys, found the error. Apprently I should only generate both Scanner and Writer when using and not as attributes. Not sure why but Writer "Overwrites" Scanner, hence all the data in duke.txt went missing
