### ISSUE TITLE
Incomplete display of background image upon resizing of GUI window

### ISSUE THREAD

**Issue by nehcuy** [nus-cs2103-AY2223S1/forum#187]
I've implemented resizing of the components to follow the corners of the page when we resize the window, but the background image does not seem to follow along. Attached below are illustrations of what I mean.
**This is the current standard starting status:**
![image](https://user-images.githubusercontent.com/94856691/189961857-347de6b1-3b37-4cdf-9e75-d09b92a35351.png)
**These are after resizing:**
![image](https://user-images.githubusercontent.com/94856691/189962085-9183e6c4-019b-4f25-a718-116ee23ef9b2.png)
![image](https://user-images.githubusercontent.com/94856691/189962099-acc3dfe4-483b-457a-bec3-219074dd5865.png)

This is my code segment for the `VBox` element in the `MainWindow.fxml` file:
```java
<content>
    <VBox fx:id="dialogContainer" prefHeight="552.0" prefWidth="388.0"
            style="-fx-background-image: url(./images/VBox-BG.png); -fx-background-size: auto;"/>
</content>
```

Here is the [link](https://github.com/nehcuy/ip/tree/branch-A-BetterGui/src/main/resources/view) to my `DialogBox.fxml` and `MainWindow.fxml` files. Any help is appreciated! 😄

**Comment by rui-han-crh** [comment]
Hi, instead of adding the background image to the dialog box, which only takes up a fixed size in height as per your format, add it to the AnchorPane of the MainWindow, which takes up the dimensions of the program window itself.
```xml
<AnchorPane maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity"
            prefHeight="600.0" prefWidth="400.0" xmlns="http://javafx.com/javafx/8.0.171"
            xmlns:fx="http://javafx.com/fxml/1" fx:controller="duke.ui.MainWindow"
            style="-fx-background-image: url(./images/VBox-BG.png)">
...
</AnchorPane>
```

However, the background will now be obstructed by the solid white ScrollPane. To make the scroll pane transparent, add a css directory under the resources folder, then add a new css file in the css directory called ScrollPane.css and format it like so
```css
.scroll-pane{
   -fx-background-color:transparent;
}

.scroll-pane .viewport {
   -fx-background-color: transparent;
}
```

Now, we can reference this css file to the ScrollPane with 
```xml
<ScrollPane fx:id="scrollPane" hbarPolicy="NEVER" hvalue="1.0"
                    prefHeight="557.0" prefWidth="400.0" vvalue="1.0" fitToWidth="true"
                    AnchorPane.leftAnchor="1.0" AnchorPane.rightAnchor="1.0"
                    AnchorPane.bottomAnchor="41.0" AnchorPane.topAnchor="1.0"
                    stylesheets="@../css/ScrollPane.css">
...
</ScrollPane>
```

This will hide the Scrollpane's opacity. So, now you can see your background

![image](https://user-images.githubusercontent.com/15359033/190039923-7415e725-2cb5-404b-8463-e7710309ef74.png)

**Comment by nehcuy** [comment]
Thank you so much for the help. No wonder I couldn't see the background image, because the ScrollPane wasn't transparent! GUI works nicely now :>

**Comment by damithc** [comment]
Thanks for the detailed help @rui-han-crh

**Comment by nehcuy** [comment]
@rui-han-crh Re-opening this because it doesn't work anymore. After i run shadowJar to build the duke.jar file, it no longer displays the background image when i run the JAR file. 🤔
