### ISSUE TITLE
Unable to run junit tests

### ISSUE THREAD

**Issue by linuschui** [nus-cs2103-AY2223S1/forum#188]
Hello I am using i5 Mac

I was attempting to add more tests for my new commands but I am running into this error 
 
<img width="1369" alt="Screenshot 2022-09-14 at 1 26 12 AM" src="https://user-images.githubusercontent.com/97402389/189968374-a5ff0ff3-fa90-41ac-baad-8039c5feada0.png">

I have added junit4 as a dependency to the test module but it is unable to solve the issue 😢 
<img width="1010" alt="Screenshot 2022-09-14 at 1 26 26 AM" src="https://user-images.githubusercontent.com/97402389/189968436-5bf5803b-cdca-4b1f-90b6-577b4d278e81.png">

Will appreciate any help, thank you!

**Comment by TanPingZhi** [comment]
I have looked through your repo and don't find anything wrong but I guess this bug is probably not pushed. Does this [link](https://stackoverflow.com/questions/30474767/no-tests-found-for-given-includes-error-when-running-parameterized-unit-test-in) help?

**Comment by damithc** [comment]
@linuschui While waiting for inputs from others, here are some things you can try:
* Push the code to a branch and share here so that other can try to replicate the problem.
* If using Intellij, try these 'common remedies' one-at-a-time in this order:
  * File -> Invalidate caches
  * Delete the .idea folder -> Close and re import the project
  * Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.

**Comment by Tan-Jia-Rong** [comment]
I have looked through you repo as well, everything looks fine. Perhaps you could consider the following solution provided [here](https://stackoverflow.com/questions/60228404/no-tests-found-for-given-includes-when-running-gradle-tests-in-intellij-idea)

## Solution 1

1. Go to Preferences -> Build, Execution, Deployment -> Gradle -> change "Run tests using" to "IntelliJ IDEA".
Run your test.
2. Go again to Preferences -> Build, Execution, Deployment -> Gradle -> change "Run tests using" to "Gradle (default)".
3. Keep running your test, it is working now.

Hopefully it works for you 😃
