### ISSUE TITLE
Copied ACTUAL.txt to EXPECTED.txt but still fails test.

### ISSUE THREAD

**Issue by CJun1039** [nus-cs2103-AY2223S1/forum#19]
I am working on the iP on Windows using IntelliJ.

My actual.txt and expected.txt are the same but the test still fails. Tried converting both files to unix format using the dos2unix on git-bash but got the same result.

![image](https://user-images.githubusercontent.com/89005851/185279281-b78f68d0-cb08-41e4-b7c5-174359c21c24.png)

**Comment by damithc** [comment]
@CJun1039 Try using Windows `CMD` terminal (instead of Gitbash terminal). Reason: you are running a `.bat` file (meant for Windows) in Gitbash (which emulates a Unix-like environment).

**Comment by leonidas1712** [comment]
Hi! I had the exact same issue and it was really annoying. When I tried comparing the files using IntelliJ itself (Select the files, right click and click 'Compare Files') I saw that it was failing due to really small, inconsequential differences I couldn't even notice when seeing the files side-by-side (see example below):

<img width="800" alt="Screenshot 2022-08-18 at 11 49 41 AM" src="https://user-images.githubusercontent.com/20151382/185289351-12a39c16-ae17-43c7-8852-b9efc3e2bf4e.png">

I am using Mac, so what worked for me was to run the `diff` command with the`-w `option, which ignores whitespace. 

**Note**: for anyone using a *nix OS it seems that -w has some nuances to it and there are other options which you may find more suitable (see this [StackOverflow](https://stackoverflow.com/questions/16423024/how-can-i-diff-2-files-while-ignoring-leading-white-space) link)

Since you are using Windows, you can try looking at the options [here](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/fc) for what I believe is the equivalent command (`FC` or File Compare, the last command in `runtest.bat`). 

I think adding the`\w` option might help? Sorry I can't test it out as I don't have access to a Windows OS or VM right now!

**Comment by CJun1039** [comment]
Thanks for the replies!

@damithc I first tried using the terminal on IntelliJ but it did not work. The reason I used git-bash is because of this part under troubleshooting (from the testing tutorial).
![image](https://user-images.githubusercontent.com/89005851/185289770-11110ed5-03b3-4dfc-abe1-833056e34ac2.png)

@huzaifa1712 The -w option worked for me!
