### ISSUE TITLE
Help with smoke tests - *nix and Mac appreciated

### ISSUE THREAD

**Issue by clarence-chew** [nus-cs2103-AY2223S1/forum#192]
Hello, I'll like to get some help with smoke tests. Here's the [JAR file](https://github.com/clarence-chew/ip/releases/tag/A-Release) and here's the [User Guide](https://clarence-chew.github.io/ip/).

Console mode is highly recommended for serious usage - run `java -jar ./Anthea.jar console` or the equivalent to run it in the console.

**Comment by Evande1** [comment]
Hello @clarence-chew, tested it on macOS and it works.

**Comment by clarence-chew** [comment]
Thanks for the help!

**Comment by Bubbl3T** [comment]
Yep, works on macOS. However, I do notice that running the `list` command cause all the tasks to display in one line instead of displaying them on separate lines. Not sure if this is intended or not, but just pointing out for your information.

Also, your code running on macOS face the same issue of not creating a data file at the file location. I am facing the same issue now and still looking for solution. Do follow the other thread [here](https://github.com/nus-cs2103-AY2223S1/forum/issues/199).
