### ISSUE TITLE
[tP] Is "Squash and merge" allowed?

### ISSUE THREAD

**Issue by RichDom2185** [nus-cs2103-AY2223S1/forum#209]
If our team is planning to use a branch-based workflow for our tP (i.e. all commits go to their own branches, and `master` only receives merges), can we use the "Squash and merge" option from GitHub?

The main focus of the question lies in the fact that unlike GitLab, for GitHub, we cannot have the option to both squash all commits of that branch into one commit and keep a merge commit (`--no-ff`) at the same time.

Are the merge commits necessary for the tP?

**Comment by damithc** [comment]
@RichDom2185 The tP work needs to follow the workflow we prescribe (i.e., the _forking workflow_), at lease in the initial iterations. The forking workflow is branch-based too. More details in the module website.

We recommend you use a regular merge commit (i.e., don't allow fast forward, don't rebase, don't squash) to preserve the exact timestamps of when the work was done. This is because the timing of work is factored into grading.

**Comment by RichDom2185** [comment]
Noted Prof, thank you!
