### ISSUE TITLE
Request for smoke testing help [Windows/Linux]

### ISSUE THREAD

**Issue by seelengxd** [nus-cs2103-AY2223S1/forum#212]
Hello! Here is my [jar](https://github.com/seelengxd/ip/releases/tag/A-Release) and [user guide](https://seelengxd.github.io/ip/)! would appreciate help to test if the jar works on windows & linux. thank you!

**Comment by Benjamin-Sim** [comment]
Hi @seelengxd, your jar works fine on Windows 👍.

Only issue is that these warnings are printed to the console every time I enter a command:

![Capture](https://user-images.githubusercontent.com/92283593/190546461-73fac860-4f4b-4790-88a1-d6ee9c721b38.PNG)

**Comment by JasonYapzx** [comment]
Hey seeleng, works fine on Windows 10 for me as well.
For the warnings mentioned by @Benjamin-Sim, it might be because in your `.fxml` files the `xmlns` tag is of JavaFX version 18. But otherwise nice UI and great  visual feedback for erroneous commands :)
![image](https://user-images.githubusercontent.com/63844743/190547625-91182de9-53cb-4109-8c73-9d361d3628f2.png)

**Comment by RezwanArefin01** [comment]
Tested on Linux (Arch).
![Screenshot_20220916_151511](https://user-images.githubusercontent.com/22095441/190579108-4076c6de-3444-4de4-9f54-b6ca27a47f22.png)

However, I can't seem to be able to run it with double clicking; then I get a 0 width/height window like this: 
![Screenshot_20220916_151653](https://user-images.githubusercontent.com/22095441/190579439-2251c684-0f89-467a-bb73-56819c0e92dc.png)

**Comment by seelengxd** [comment]
Thanks for the help! :D
