### ISSUE TITLE
Request for help to smoke test (linux,MacOS)

### ISSUE THREAD

**Issue by xhphoong** [nus-cs2103-AY2223S1/forum#217]
Hi, would appreciate if anyone can help with the smoke test in linux, MacOS and Windows ? 
This is my [jar file](https://github.com/xhphoong/ip/releases/tag/v.03-A-Jar) and [user guide](https://xhphoong.github.io/ip/).
Thank you so much !!

**Comment by parth-io** [comment]
![image](https://user-images.githubusercontent.com/67057645/190584337-46ca454c-3e05-4be6-b0ba-27f906da591c.png)

Tested the commands on Linux (Kubuntu) with Java 11 - the images do not load, but all the commands work well and the file `./data/duke.txt` is loaded on subsequent launches properly

**Comment by xhphoong** [comment]
@parth-io Noted, thank you!

**Comment by xhphoong** [comment]
> ![image](https://user-images.githubusercontent.com/67057645/190584337-46ca454c-3e05-4be6-b0ba-27f906da591c.png)
> 
> Tested the commands on Linux (Kubuntu) with Java 11 - the images do not load, but all the commands work well and the file `./data/duke.txt` is loaded on subsequent launches properly

Hi, just wanna ask one more thing is there a font differences between an error message (eg when u randomly type sth) and normal message? Thank you!

**Comment by xhphoong** [comment]
@parth-io and may I ask one more thing? Is there a text difference in the error messsage (eg when randomly type sth) and the normal message? Thank you!

**Comment by parth-io** [comment]
It's strange, the code you wrote is pretty much identical to mine in terms of the structure and method calls, so I'm not sure why the images are not loading - I'll try cloning the repo and building the jar locally

Yep, there's a difference

![image](https://user-images.githubusercontent.com/67057645/190587575-390c886e-98d2-465d-bfee-15fad876252b.png)
![image](https://user-images.githubusercontent.com/67057645/190587637-24426dc8-299e-4b73-99f8-5a2e6c98f64b.png)

**Comment by xhphoong** [comment]
@parth-io Thank you!

**Comment by RezwanArefin01** [comment]
The fonts are not included in the jar. So we have to reply on the user having the fonts installed :disappointed: I am seeing it like this on Linux (Arch with KDE too, but different from above): 
![Screenshot_20220916_161843](https://user-images.githubusercontent.com/22095441/190591649-c6ad7298-23b8-492f-9804-9d97fcf3394a.png)

**Comment by carriezhengjr** [comment]
I'm using MacOS and this is what appears.
<img width="398" alt="Screenshot 2022-09-16 at 16 32 33" src="https://user-images.githubusercontent.com/97394017/190594654-f66dcf26-1700-499d-9b0b-9550078e1bf8.png">

**Comment by parth-io** [comment]
I think I figured out why the images are not loading (for me at least): 

Try adding the two print lines to `MainWindow::setAnya`. 
```
    public void setAnya(Anya a) {
        System.out.println("Image loading error? " + userImage.exceptionProperty());
        System.out.println("Image loading error? " + userImage.getException());
        anya = a;
        String greet = a.start();
        dialogContainer.getChildren().addAll(
            DialogBox.getAnyaDialog(greet, anyaWelcomeImage)
        );
    }
```

The output I get is:
```
Image loading error? ReadOnlyObjectProperty [bean: javafx.scene.image.Image@36927683, name: exception, value: java.io.IOException: Wrong JPEG library version: library is 80, caller expects 70]
Image loading error? java.io.IOException: Wrong JPEG library version: library is 80, caller expects 70
```

Apparently this has to do with the `libjpeg` library version that's being called by the jar file. @RezwanArefin01 do you have the same issue?

Dependency versions in `build.gradle` are as expected. I can't figure out how to force Java to bundle this specific version of `libjpeg` (also this issue doesn't happen for my own repo)

**Comment by RezwanArefin01** [comment]
Yes I got the same error message: 
```
Image loading error? ReadOnlyObjectProperty [bean: javafx.scene.image.Image@e2cb9ac, name: exception, value: java.io.IOException: Wrong JPEG library version: library is 80, caller expects 70]
Image loading error? java.io.IOException: Wrong JPEG library version: library is 80, caller expects 70
```

The `.fxml` files seems to be using javafx version 8 (probably due to installing older version of scene builder?). I changed them to 11, but that didn't fix it.

I've done a lot of smoke testing. Seems like a lot of students have this issue. Only a few ran correctly on my system.

**Comment by parth-io** [comment]
Wow, this is a tricky problem. Just curious, where did you change the version for the `.fxml` files? In `build.gradle`?

Is it still unresolved for the other students?

**Comment by RezwanArefin01** [comment]
Okay, I managed to fix the problem. Googling seemed to suggest that the problem is with the images themselves. So I converted the `.png`s to `.jpg` and then converted them back to `.png`. Now the images are loading correctly: 
![Screenshot_20220916_172137](https://user-images.githubusercontent.com/22095441/190604206-89c830aa-c339-4241-9964-fcda476bdb9c.png)

If I have to guess: the images are corrupted somewhere. Maybe copied from web and pasted locally and not downloaded properly?

**Comment by xhphoong** [comment]
Noted, thanks @RezwanArefin01 @parth-io @carriezhengjr. I will try fix the font and image issue.

**Comment by xhphoong** [comment]
Hi, this is the new [jar file](https://github.com/xhphoong/ip/releases/tag/v.04-A-Jar), would appreciate if someone could help to check it on linux and macos again to see whether this time the font type and image display out correctly? @parth-io @RezwanArefin01 @carriezhengjr  Thankss

**Comment by carriezhengjr** [comment]
Hi! I have downloaded the new jar file, but I'm not sure why I could not open it on my Mac. Seems like it's running because I have the "java" folder icon showing in the bottom bar (which always show when I run jar files), but the window is not showing up. I tried to click "Show All Windows" but I got "No Available Windows".

I have tried to delete and re-download it several times, the window to the app still does not show up.

Perhaps you could try to re-upload your jar file?

**Comment by xhphoong** [comment]
@carriezhengjr Thanks,  I reposting a new issue for the new jar file.
