### ISSUE TITLE
Request smoke test for MacOS/Linux

### ISSUE THREAD

**Issue by sugiyem** [nus-cs2103-AY2223S1/forum#242]
Hi all, would really appreciate if anyone can help me test my [app](https://github.com/sugiyem/ip/releases) on MacOS and Linus. You can view my User Guide [here](https://sugiyem.github.io/ip).

Thank you!

**Comment by chloeelim** [comment]
Hi, tested on MacOS and seems to be working fine. Not sure if this was intended, but there's a weird character (see below) that appears when you input an invalid command.

<div display = "flex">
  <img width="397" alt="Screenshot 2022-09-17 at 6 20 23 PM" src="https://user-images.githubusercontent.com/79991214/190852143-9638bc83-393c-4d3f-8dae-726795a7c2f3.png">
  <img width="389" alt="Screenshot 2022-09-17 at 6 21 43 PM" src="https://user-images.githubusercontent.com/79991214/190852154-92247c82-d753-482d-b4fb-56fd41a32a5a.png">
</div>

**Comment by Nephelite** [comment]
I ran your jar file in my Linux VM. Perhaps this isn't an accurate test, but...

![image](https://user-images.githubusercontent.com/97427604/190853004-c23a5229-9d67-4895-a0bf-9cf11d7b031a.png)
![image](https://user-images.githubusercontent.com/97427604/190853020-e0a9d837-2ee5-44d4-a6cd-f7a188efdf2a.png)

Below is the first block of exceptions I get before an infinite loop of NPEs
![image](https://user-images.githubusercontent.com/97427604/190853087-e4ee303d-7941-4c85-b094-705c5f7370a8.png)

Apologies, but I can't paste the block of exceptions as a code block because I am running your jar file on a VM. 

Your jar file starts up fine on Linux VM.

However, I got this exception whenever I try to run any command on Linux. I suspect the reason is that your userImage is an image in ```.jpg``` format. According to RezwanArefin01 in [this thread](https://github.com/nus-cs2103-AY2223S1/forum/issues/217), changing the image to a ```.png``` format should fix the issue.

**Comment by sugiyem** [comment]
@Nephelite thank you for the suggestion. I've updated the jar file.

**Comment by Nephelite** [comment]
@sugiyem Everything seems in order
![image](https://user-images.githubusercontent.com/97427604/190889198-8c2b3a73-f234-48ea-9371-4937cf8f6963.png)

However, before you close this thread (if you are only waiting on a Linux response), I wanted to mention [this thread](https://github.com/nus-cs2103-AY2223S1/forum/issues/246). This issue applies to your JAR file too, so do give it a look. I didn't mention it in my prior post because I did not know about it at the time. If you want me to test this again, let me know!

Edit: Also, add ```id 'org.openjfx.javafxplugin' version '0.0.10'``` into your plugins in ```build.gradle``` if you want to do the changes in the thread I mentioned

**Comment by Nephelite** [comment]
To add on, the javafk block should be directly below the plugins block.

**Comment by sugiyem** [comment]
@Nephelite Thanks for the input. Could you help me check my updated [jar](https://github.com/sugiyem/ip/releases) file?

**Comment by Nephelite** [comment]
@sugiyem 

![image](https://user-images.githubusercontent.com/97427604/190907783-13bb3ce0-5adb-4860-98f7-4e1e1f438a79.png)

Yep, works for me now with just ```java -jar```.

Do ask for a mac user to test again though, since you have made big changes to your build. Ensure they are using zulu jdk 11 as indicated by the module website.

**Comment by RezwanArefin01** [comment]
Works as expected on Linux (Arch). However I'd suggest you to disable window resize by `stage.setResizeable(false);`, if you are not planning on wrapping it properly.
![Screenshot_20220918_215017](https://user-images.githubusercontent.com/22095441/190909302-472ab2a9-e807-45cc-89a6-4f26073a4c2a.png)

**Comment by sugiyem** [comment]
Thanks all!
