### ISSUE TITLE
Unable to open jar file on windows using Java SE binary but able to open jar file on IntelliJ

### ISSUE THREAD

**Issue by qiaoen17** [nus-cs2103-AY2223S1/forum#249]
Hello, I went to try to fix my Storage.java and Duke.java as it was not generating text files on other computers, basically an issue with the save function in my latest commit. Before, I was able to run the jar file generated via Java SE binary without the changes, but now I am unable to and the jar file generated only runs in IntelliJ when I run duke.jar.

I tried running it in ubuntu via java -jar duke.jar but got the error below:
![Screenshot (235)](https://user-images.githubusercontent.com/92434807/190889322-015e0d1e-f29d-490f-bd28-4ee82ab47e3e.png)

Not very sure how to solve this error and I can't really find solutions online either.

**Comment by RussellDash332** [comment]
See #118. (edit: sorry, tagged the wrong issue :D)

**Comment by qiaoen17** [comment]
Hello, I saw the issue #118 and I concluded ubuntu most likely does not support GUI. To clarify, I tried running the jar file on ubuntu as I was unable to run jar files on my command prompt and I wanted to see why **duke.jar is able to open and run on IntelliJ** but **not on Java SE binary** . I thought the error was related to why duke.jar would not open on Java SE Binary, but I see that is not the case. 

I'm not sure how to debug why it does not run on Java SE binary but it is able to run in IntelliJ, so I think that would be my main issue now :(

**Comment by damithc** [comment]
@qiaoen17 Are you using WSL?

**Comment by qiaoen17** [comment]
@damithc Nope, I'm using windows. 

![Screenshot (236)](https://user-images.githubusercontent.com/92434807/190906190-4195aede-9147-47fd-b53b-94d2ffe3b651.png)

Unable to run using Java SE Binary

**Comment by damithc** [comment]
> @damithc Nope, I'm using windows.

I meant, how did you do the below? If you used a WSL terminal (which is a Linux terminal running inside Windows), the error is expected as most WLS versions doesn't support GUIs. 

> I tried running it in ubuntu via java -jar duke.jar but got the error below:
> ![Screenshot (235)](https://user-images.githubusercontent.com/92434807/190889322-015e0d1e-f29d-490f-bd28-4ee82ab47e3e.png)

**Comment by Eclipse-Dominator** [comment]
Hello, you can open GUI with WSLg if you are on windows 11. 
But you need to updated your javafx dependency to the latest version. If not you will encounter `gdk_x11_display_set_window_scale: assertion 'GDK_IS_X11_DISPLAY (display)' failed` error when trying to open it. A work around is to add the `-Djdk.gtk.version=2` flag when running the jar file.
![image](https://user-images.githubusercontent.com/4567895/190913030-47bff9d2-6f83-4a36-811d-16a69dd12187.png)

You can probably open the the jar file with intellij because your intellij is running a jdk installation located on windows (which means that you are likely running it on windows). For the screenshot above, `/mnt/c/` is a sign that you are running on WSL which is running on your ubuntu distro (not your windows). Since it looks like you are using windows 10, it is unlikely you will be able to get gui to work (maybe you can try using win-kex but doing that is not really worth imo

**Comment by qiaoen17** [comment]
Ah thank you, I'll close this issue then.
