### ISSUE TITLE
"UnsatisfiedLinkError: Can't load library" when running addressbook.jar on M1 Mac

### ISSUE THREAD

**Issue by WuHaohui1231** [nus-cs2103-AY2223S1/forum#25]
I followed this guide to check the compatibility of my M1 Mac to the JAR files.
<img width="655" alt="image" src="https://user-images.githubusercontent.com/95847459/185327793-85ed1dc7-f70a-4b30-b8ab-d416bccb2af4.png">

The Java 11 on my Mac works well when I am doing the iP. But this issue happened when I run `java -jar addressbook.jar`.

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/95847459/185325493-41e478a9-adc6-4686-b758-d9573ab17b93.png">
Is this the expected behaviour of incompatibility? However, it seems the guide means that a GUI should be launched without error, in which some text (whether garbled or not) will appear, even when there is incompatibility.<br/>
Or is this associated with some problem in my dependencies setup?<br/>
Thank you!

**Comment by damithc** [comment]
> Is this the expected behaviour of incompatibility? However, it seems the guide means that a GUI should be launched without error, in which some text (whether garbled or not) will appear, even when there is incompatibility.

@WuHaohui1231 This is certainly not the expected behavior. A GUI should appear instead. Let's wait to hear from other Mac users how they fared with this. I suspect the advisory applies to you and you need to install the exact JDK we have specified (as per the advisory). But it's not urgent. Good enough if you can fix this within the next 2 weeks or so.

**Comment by ngshijun** [comment]
Same issue happened to me. I think it's due to you not using the exact JDK specified by the teaching team (Azul build of OpenJDK 11). Issue should be resolved one the correct version of JDK is used.

**Comment by sikai00** [comment]
Can confirm @ngshijun is right. Managed to replicate the same exact error with Oracle Java 18.0.2. 

Try running `where java` in your terminal (I'm assuming you are using zsh). It should output something like this:
<img width="534" alt="image" src="https://user-images.githubusercontent.com/63795894/185473540-6863fdd1-230a-4118-b487-bdaf7a48004c.png">

The 2nd line refers to the Azul Java folder in my computer's directory (yours may be different depending on where you put your Azul Java folder). zsh will prefer to use the 1st Java it can find (in this case /usr/bin/java) which is Oracle Java, so the fix is simply to let zsh "see" your Azul Java installation first. 

Simply go to your root directory (perform a `cd`), then do `vim .zshrc` which opens the config file for zsh.
Then, add this line into your .zshrc:
`export PATH='<your Azul Java folder>':$PATH`
Note that your directory should include 'bin' per my screenshot.

It should look like this now (might vary on your machine):
<img width="529" alt="image" src="https://user-images.githubusercontent.com/63795894/185741763-2f5ec860-6711-4518-9e53-8e716370bef0.png">
_(Edit: Make sure JAVA_HOME leads to the installation folder of Azul rather than bin for Gradle to identify the correct JVM to use, otherwise it will say that it is an invalid Java installation.)_
Save it, restart your terminal, then verify that Azul Java comes first by performing `where java` again (`java --version` can also verify your Java version).
<img width="538" alt="image" src="https://user-images.githubusercontent.com/63795894/185475037-75f03b44-d186-48a3-a807-25c867dac638.png">

If you don't see 2 lines (referring to the two different Java installation), it means that you probably haven't set the installation of Azul Java to your path. You can perform the same steps as above (to add Azul Java to your PATH) and it should still work.
