### ISSUE TITLE
Have a GUI that does not incorporate duke

### ISSUE THREAD

**Issue by DarrenCsAcc** [nus-cs2103-AY2223S1/forum#258]
Hi Guys,

I have a GUI but unfortunately, it is not incorporated with the duke.
I was wondering if anyone has any advise on how to resolve this.
I followed the instructions for creating the GUI but i am not sure what went wrong
I will work on my other parts first.

https://github.com/DarrenCsAcc/ip

![image](https://user-images.githubusercontent.com/89026703/190922984-4803aa14-06c1-45f9-b8a3-f09305b69be6.png)

Thank you!

**Comment by seelengxd** [comment]
Hm... went to peek at your code.

So firstly, based on these 2 extracts, we know one way is we want `Duke.getResponse(input)` to return your duke output to be "incorporated with the duke"

`MainWindow.java`
```
@FXML
private void handleUserInput() {
    String input = userInput.getText();
    String response = duke.getResponse(input);
    dialogContainer.getChildren().addAll(
            DialogBox.getUserDialog(input, userImage),
            DialogBox.getDukeDialog(response, dukeImage)
    );
    userInput.clear();
}
```

`Duke.java`
```
public String getResponse(String input) {
    return "Duke heard: " + input;
}
```

Currently, your duke logic is... in one method in the while loop of `Parser.java`. (I would recommend breaking it up if you have time)

I think the most direct method (**tho prob not the cleanest way**) is to extract out just the logic inside this while loop into a new method first in Parser.java so it takes in a String input and returns the message you want the GUI to send.

Then, inside `getResponse` of `Duke.java`, return the result of calling this new method with the input.

Hope this helps :D

**Comment by DarrenCsAcc** [comment]
@seelengxd 
Hi Thanks for the reply.
Can i just check am i suppose to rewrite my parser method?
Do i have to change my main method?
Is there a bit of an example ?
I am abit lost :(

Thank you!

**Comment by damithc** [comment]
@DarrenCsAcc @seelengxd's advice above should give you a good start. Some general tips:

You can use the [iP code dashboard](https://nus-cs2103-ay2223s1.github.io/ip-dashboard/?search=&sort=groupTitle&sortWithin=title&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=true&checkedFileTypes=java~md~fxml~sh~bat~gradle~txt) to see how others have done the  relevant parts of the code.

From the [iP showcase](https://nus-cs2103-ay2223s1.github.io/website/admin/ip-showcase.html) you can find which iPs have a simple GUI, closer to the one given in the tutorial.

**Comment by DarrenCsAcc** [comment]
Basically i talked to one of my group mate.
My code uses a while loop and therefore it does not fit into the entire logic of the GUI since i am not returning a string.
As such.... i need to do a major overhaul...(if its even possible)......
I am really finished....

Thanks for everyone's help still.
I just dont know...

**Comment by damithc** [comment]
@DarrenCsAcc You managed to get the GUI working, which is a good sign.
The rest of the code is not easy to integrate due to its current flawed structure -- mainly, due to putting all the work (reading user input, parsing the input, executing the command) inside one method. There is no easy way out of this. First, you need to restructure the existing code (used by the text UI) before you can integrate the GUI. This part is even more important than learning how to write GUIs.

Here's one approach (the result will not be ideal, but closer to current code than an ideal solution):
1. Rename `Parser` as `Logic`, as it is doing more than just parsing.
2. Instead of printing output all over the place, collect those strings in a variable and print them only at the end of the loop. This will make the following steps easier.
3. extract out a `setup` method that does the initial setting up e.g., create the file if missing
4. extract out a `readCommand` method that reads the input from the user
5. extract out an `execute` method that takes a command, does the work expected by the user, and return the string to be displayed to the user

After that, you should be able to write something like this:
```java
Logic.setup();
String command = Logic.readCommand();
while (!command.equals("bye")){
    result = Logic.execute(command);
    System.out.println(result);
    command = Logic.readCommand();
}
```

After the above, it will be easier to link up the GUI with the rest e.g.,
```java
public String getResponse(String input) {
    return Logic.execute(command);
}
```

**Comment by DarrenCsAcc** [comment]
Ok thank you i will try it now prof

**Comment by DarrenCsAcc** [comment]
![image](https://user-images.githubusercontent.com/89026703/190979133-d0c22403-6ebb-4d3b-8c34-e66dec58597a.png)

Finally managed to fix one command.Its a small step but i have to continue working towards to end goal of pivoting out of this while loop.
At least there is a glimmer of hope

**Comment by damithc** [comment]
> Finally managed to fix one command.Its a small step but i have to continue working towards to end goal of pivoting out of this while loop.
> At least there is a glimmer of hope

Nice! 👍 Keep going @DarrenCsAcc . We can give you more time for the final submission, if needed.

**Comment by DarrenCsAcc** [comment]
I managed to rectify the bulk of it to get it to work.
The quality is nowhere near as good as most of my peers but at least I got about 90% of it to work.
I am almost done with the rest of the task hopefully I can get it done by tonight. 
I will request the smoke test in another thread.

Thanks you all for your help @damithc @seelengxd @My tp team
