### ISSUE TITLE
Request for smoke test help (Windows, Linux or Mac)

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2103-AY2223S1/forum#280]
My release can be found [here](https://github.com/cheeheng/ip/releases/tag/A-Release). Could you please help me test the jar file?

**Comment by t1mzzz** [comment]
Hi!

I'm on Windows 11 and your JAR file works fine. 👍 

<img width="296" alt="image" src="https://user-images.githubusercontent.com/97350034/191345722-f3e74d56-960d-46a2-b089-59cf984016f5.png">

**Comment by RussellDash332** [comment]
LGTM! (Windows)
Resizing is also okay.

![image](https://user-images.githubusercontent.com/63991775/191354844-5e54e0e2-4a60-4148-b284-d3fbe08329f7.png)

**Comment by rui-han-crh** [comment]
HI, I'm running a Linux (Ubuntu) VM.

<img src="https://user-images.githubusercontent.com/15359033/191357441-2d81ca2b-5da7-43c7-b4c5-bd2b38f6221f.png" width="300">


All operations work fine. However, the profile picture for the responder doesn't appear. It's likely due to the image that it uses,`ManSmilingBehindWall.jpg`, being in the `jpg` format. Try converting this image to `png` for it to show on Linux machines. Reference to issue #217.

By the way. on Ubuntu 22.04.1, there's an issue with the JAR file not opening on double clicking, it can only opened upon forcing it with

```
java -Djdk.gtk.version=2 -jar jude-0.3.jar
```

It's an issue relevant to #246. Updating the `javaFxVersion` string in the `dependencies` block of the `build.gradle` file from `11` to `11.0.2` may fix this.

**Comment by sltsheryl** [comment]
It's working well on mac. It resizes correctly too!
<img width="588" alt="Screenshot 2022-09-21 at 10 54 50 AM" src="https://user-images.githubusercontent.com/96589109/191404106-4eb741eb-d714-43cd-a65c-550fb05cbab1.png">

**Comment by cheeheng** [comment]
Thanks @rui-han-crh for the great help! I followed your suggestion and got it to work on Linux (at least on my machine). I have updated my jar file. Please test again to make sure it works.

**Comment by cheeheng** [comment]
Thanks @rui-han-crh for the great help! I followed your suggestion and got it to work on Linux (at least on my machine). I have updated my jar file. Please help me test again to make sure the jar file works.

**Comment by rui-han-crh** [comment]
@cheeheng 

The images are working well now. I'm personally still not able to double click to open and must still use `-Djdk.gtk.version=2` but maybe this is just a thing on Ubuntu 22.04. But everything else looks and works fine now.

![image](https://user-images.githubusercontent.com/15359033/191647366-c818d1ff-672e-4dc4-9f8b-5b322976f383.png)

**Comment by cheeheng** [comment]
For Linux users, does `java -jar jude-0.3.jar` work?

**Comment by cheeheng** [comment]
Thanks @rui-han-crh for your feedback. I have updated my release. For Linux users, does `java -jar jude-0.3.jar` work now?
