### ISSUE TITLE
Request for smoke test help (Windows/Linux/Mac)

### ISSUE THREAD

**Issue by ryanguai** [nus-cs2103-AY2223S1/forum#281]
My release can be found [here](https://github.com/ryanguai/ip/releases/tag/v0.3). Could you please help me test the jar file?

**Comment by rui-han-crh** [comment]
Hi, I'm running a Linux (Ubuntu) VM.

Currently, the images do not show on Ubuntu:
<img src="https://user-images.githubusercontent.com/15359033/191352006-71dd0829-3722-488a-95e8-6809cbf3ba59.png" width="300">

I took a look at your resources folder and this is likely because your images are in the `jpeg` format. Try converting your images into `png` format for them to appear on Linux. Reference to #217 [relevant fix](https://github.com/nus-cs2103-AY2223S1/forum/issues/217#issuecomment-1249137283).

For some reason, the `bye` command doesn't close the program, I have to manually close it myself.

There seems to be an issue with the vertical height of the dialog box not expanding past its fixed height. It doesn't seem to be able to display more than 4 or 5 tasks, even though the tasks exist.

<img src="https://user-images.githubusercontent.com/15359033/191355151-99617325-f55b-48b7-991c-baf567d80f51.png" width="300">

Other than that, the program works fine. The window is resizable though, but the dimensions of the scroll pane don't follow, maybe lock the screen size, or anchor the scrollpane, submit button and text field to the relevant corners of the window so they follow the window dimensions.

**Comment by RussellDash332** [comment]
Hi, currently using Windows. Overall it looks fine to me.

<img src="https://user-images.githubusercontent.com/63991775/191355319-0885c78f-5e76-4dc6-be25-507ca5ea48e6.png" width="50%">

Some inputs that might cause an error (not sure if this is a feature to not handle anything or a bug):
- `event a /at`
- `mark 3` (only < 3 tasks in the list)

But it would be a good if there's exception handling for this.

Your windows seems to be off when being resized. If you don't want to fix this, you can disable resizing by adding `            stage.setResizable(false)` to your `Main.java` code. (example: [this line](https://github.com/RussellDash332/ip/blob/master/src/main/java/stashy/launcher/Main.java#L28))

**Comment by sltsheryl** [comment]
The pictures are okay on mac. But yea, I can't input invalid commands like what the others mentioned, it's not handled. 
<img width="586" alt="Screenshot 2022-09-21 at 10 51 31 AM" src="https://user-images.githubusercontent.com/96589109/191403619-936b3c01-91ae-490b-97b4-f8bd408dd9f1.png">

**Comment by ryanguai** [comment]
> There seems to be an issue with the vertical height of the dialog box not expanding past its fixed height. It doesn't seem to be able to display more than 4 or 5 tasks, even though the tasks exist.

Thanks everyone! Any suggestions how to make the dialog box resize automatically? I'm not so sure how to implement this.

**Comment by RussellDash332** [comment]
#128 might [help](https://github.com/nus-cs2103-AY2223S1/forum/issues/128#issuecomment-1235436752) to resolve the issue!

**Comment by ryanguai** [comment]
Thanks Russell!
