### ISSUE TITLE
Request for Smoke Test  (MacOS)

### ISSUE THREAD

**Issue by xhphoong** [nus-cs2103-AY2223S1/forum#282]
Hi, would appreciate if anyone can help with the smoke test for my new jar? 
Here is my [jar](https://github.com/xhphoong/ip/releases/tag/A-Release) and my [user guide](https://xhphoong.github.io/ip/). 
(Maybe can test the function ,type something random, change the format of stored data file and reopen and see how it reacts and post a ss here)
Thank You so Much!

**Comment by RussellDash332** [comment]
Works on Windows for all the happy paths :)

I like how this happens when I change the data file.
![image](https://user-images.githubusercontent.com/63991775/191406891-3836b95f-1de0-46cd-ba49-980631f6817f.png)

However, some non-happy paths to consider:
- `event test /by`
- `event test /at`
![image](https://user-images.githubusercontent.com/63991775/191406745-54d48535-19ba-49c0-83c2-b648f0adbb48.png)

**Comment by Yongbeom-Kim** [comment]
Works on Ubuntu WSL as well.

When data file is changed:
![image](https://user-images.githubusercontent.com/63487502/191412823-17c14eba-e475-4f7d-9333-6e59dbc22631.png)

On invalid command:
![image](https://user-images.githubusercontent.com/63487502/191413027-79c4d784-f4b7-473d-9607-01f4476bd527.png)

**Comment by xhphoong** [comment]
@Yongbeom-Kim @RussellDash332 Thanks for testing! : )

**Comment by yuehernkang** [comment]
![](https://i.imgur.com/zHmBRxk.png)

works fine in MacOS! 

![](https://i.imgur.com/9lmJls0.png)

when data file changed

**Comment by xhphoong** [comment]
Thank you so much ! @yuehernkang
