### ISSUE TITLE
[A-TextUiTesting] nothing in Actual

### ISSUE THREAD

**Issue by PokezardVGC** [nus-cs2103-AY2223S1/forum#29]
![image](https://user-images.githubusercontent.com/71965541/185427885-2a3fa531-746b-44bf-981f-f36bd1793895.png)
![image](https://user-images.githubusercontent.com/71965541/185427916-d708e29f-1c03-49b3-b5ff-845a1ccd22b7.png)
![image](https://user-images.githubusercontent.com/71965541/185427933-6668f5a7-8696-4483-be51-3943ad6648b8.png)
As shown there are inputs and EXPECTED filled up but when I run rentest.sh, nothing appears in ACTUAL. Anyone encountered the same issure and happen to know why?

**Comment by damithc** [comment]
@PokezardVGC you can push your code to your fork and share the link here so that others can try to reproduce the problem.

**Comment by PokezardVGC** [comment]
Link here: https://github.com/PokezardVGC/ip
thanks for the tips prof

**Comment by leonidas1712** [comment]
Hi, I tried cloning your repo and running the code. I think the reason you don't get anything in ACTUAL.TXT is because your Duke.java file does not output anything. The output from the main method in Duke.java (through `System.out`) is what is written to ACTUAL.TXT when you run `runtest.sh`.

If you try uncommenting the print statement in Duke.java and running `runtest.sh` again you might be able to see some output in ACTUAL.TXT!

**Comment by PokezardVGC** [comment]
Thanks @huzaifa1712 ! Old habits of naming everything main and not noticing it's supposed to be called Duke. Really silly mistake on my part.

**Comment by damithc** [comment]
Thanks for helping @huzaifa1712 💯
