### ISSUE TITLE
Sync fork button to sync team repo

### ISSUE THREAD

**Issue by sltsheryl** [nus-cs2103-AY2223S1/forum#324]
Hi can I ask on the website, it says to sync our team repo, we should do git pull then git push to our own fork.

<img width="400" alt="Screenshot 2022-10-01 at 1 55 51 PM" src="https://user-images.githubusercontent.com/96589109/193395086-cfd50143-f299-45e7-9cd9-f1738dddc9a1.png"> 

Just to check, we can also use Sync fork on GitHub? It won't affect how the grading checks for our forks, etc.?
Thanks!

<img width="400" alt="Screenshot 2022-10-01 at 1 56 38 PM" src="https://user-images.githubusercontent.com/96589109/193395097-92640300-0edc-426b-a78d-757fe47f1310.png">

**Comment by damithc** [comment]
@sltsheryl yes you can use that too, but we recommend you learn (and use for a while at least) the more basic method given in our website. Reasons:
1. 'Sync fork' is a Github-specific feature while our method works even if you are not using GitHub. This is important as the companies you will intern at might not be using GitHub.
2.  You have more control (e.g., you can decide the exact commit message) when you sync locally rather than remotely

**Comment by sltsheryl** [comment]
> @sltsheryl yes you can use that too, but we recommend you learn (and use for a while at least) the more basic method given in our website. Reasons:
> 
> 1. 'Sync fork' is a Github-specific feature while our method works even if you are not using GitHub. This is important as the companies you will intern at might not be using GitHub.
> 2. You have more control (e.g., you can decide the exact commit message) when you sync locally rather than remotely

Yes I see, thank you!
