### ISSUE TITLE
Git Fetch

### ISSUE THREAD

**Issue by junlee1991** [nus-cs2103-AY2223S1/forum#326]
If i want to checkout / contribute to my teammate's PR, 

do i use `git fetch <url>` to load that branch to my com? 
is it git checkout?

**Comment by nehcuy** [comment]
I found a solution to this [online](https://tighten.com/blog/adding-commits-to-a-pull-request/). Basically you can add your teammate's fork as a remote repo to your local repo. However, this requires your teammate to check the "Allow edits from maintainers" checkbox on the Pull Request.

If you need to edit small things urgently, you can instead follow this [solution](https://stackoverflow.com/questions/44030176/how-to-modify-someone-elses-github-pull-request):
- Head to the PR and click "Files Changed" tab at the top. 
- Click on the blue "+" button that appears and comment out whatever changes you think needs to be done.
- Merge the branch as if there was nothing wrong.
- Make a new commit to your repository that fixes the issues (preferably mentioning the PR by issue id in your commit message so that GitHub can tell it's related and show it in the PR's Conversation page).

**Comment by leonidas1712** [comment]
You can also try installing the [Github CLI](https://cli.github.com/) if you want,which makes it easier to checkout someone else's PR,.
