### ISSUE TITLE
UI Testing

### ISSUE THREAD

**Issue by ElginL** [nus-cs2103-AY2223S1/forum#328]
Hi, I'm in the process of updating my tp's application UI, but I can't pass the code coverage CI.

The code coverage report states that I have certain lines not covered by tests, such a snippet from `MainWindow.java`:

```java
StatusBarFooter statusBarFooter = new StatusBarFooter(logic.getJeeqTrackerFilePath());
statusbarPlaceholder.getChildren().add(statusBarFooter.getRoot());
```

However, I have no idea how I can create test cases for these cryptic lines, and from what I observe, most of the pre-built UI that is given at the start aren't covered by test cases as well (such as the classes in UI folder). So, I'm quite confused as to what is required.

Can anyone give me an approach to solve this? Thanks

**Comment by damithc** [comment]
Some options:
* Ignore the failure and merge the PR (probably needs admin permissions to do this)
* Tweak CI configuration to relax or remove the CI check for code coverage

Note that while it is possible to cover GUI code using automated tests, it takes a lot of effort to do so. In fact AB4 (which was used as the base for the tP sometime back) has such automated GUI tests, using the TestFX framework. Later we changed the tP to use AB3 as the base (the main difference between AB3 and AB4 at the time was the lack of automated GUI testing in AB3) because some students found it too hard to maintain the GUI tests in AB4. GUI tests in general breaks easily (e.g., depends on the screen resolution) and harder to debug when that happens.

**Comment by ElginL** [comment]
Okay, thank you prof 👍
