### ISSUE TITLE
[Code Dashboard] iP code not shown in code dashboard

### ISSUE THREAD

**Issue by maryjess** [nus-cs2103-AY2223S1/forum#33]
My iP code is not shown in the code dashboard, however its progress is shown in the progress dashboard. 
To my understanding, the dashboards are updated daily, and my last update to the code was yesterday afternoon. 
For this case, should I just wait for the code dashboard to be updated, or is there anything I should do?

**Comment by damithc** [comment]
@maryjess It depends on when the code was pushed to GitHub, rather than when the code was committed. Yes, you can wait one more day and let me know if the code is still not updated. You can see the last updated time of the code dashboard at the bottom of the page.

![image](https://user-images.githubusercontent.com/1673303/185597455-4494efb8-f7a3-42ff-9004-4d04ef24692e.png)

**Comment by maryjess** [comment]
Yes, by update I meant pushing to GitHub. I checked again just now and the code is still not updated. The dashboard shows that the last updated time was this morning though.
![image](https://user-images.githubusercontent.com/88389105/185725827-3305a670-9f02-492b-9a93-a775dac9e54e.png)

**Comment by damithc** [comment]
@maryjess it was because your git author name was not the same as your GitHub username (see https://nus-cs2103-ay2223s1.github.io/website/admin/tools.html#tool-git-for-revision-control ) We have updated our config files to include the Git author name you used. Should be fine now.

**Comment by maryjess** [comment]
I see. Thank you Prof!
