### ISSUE TITLE
CI for build (ubuntu-latest) takes very long

### ISSUE THREAD

**Issue by carriezhengjr** [nus-cs2103-AY2223S1/forum#333]
I have changed [build.gradle](https://github.com/carriezhengjr/tp/blob/gui-testing/build.gradle) to include TestFX for automated GUI testing in an attempt to solve the failing codecov/patch check #330 that appeared from my previous commit. 
However, [build (ubuntu-latest)](https://github.com/carriezhengjr/tp/actions/runs/3210434980/jobs/5248668231) is taking super long (> 1 hour) while [build (macos-latest)](https://github.com/carriezhengjr/tp/actions/runs/3210434980/jobs/5248668277) and [build (windows-latest)](https://github.com/carriezhengjr/tp/actions/runs/3210434980/jobs/5248668318) took less than 2 minutes each.
<img width="1483" alt="Screenshot 2022-10-09 at 00 36 03" src="https://user-images.githubusercontent.com/97394017/194717902-df0b8785-fd63-47e3-a23c-56bd1235e2c8.png">

Is it because I have missed out some things when adding automated GUI testing using TestFX? But why does it work with macos and windows 🤔 ?
(The [tests](https://github.com/carriezhengjr/tp/tree/gui-testing/src/test/java) that I've added are for [`HelpWindow.java`](https://github.com/carriezhengjr/tp/blob/gui-testing/src/main/java/seedu/address/ui/HelpWindow.java). They are mostly reused and adapted from the GUI tests written in [Address Book (Level 4)](https://github.com/se-edu/addressbook-level4).)

**Comment by damithc** [comment]
@carriezhengjr  did you try restarting the CI job?
On a related note, GUI tests are more susceptible to OS-specific quirks.

**Comment by carriezhengjr** [comment]
> @carriezhengjr did you try restarting the CI job? On a related note, GUI tests are more susceptible to OS-specific quirks.

Yes, I have cancelled the 1st attempt and tried again, but it's still not done running the check. The [1st attempt](https://github.com/carriezhengjr/tp/actions/runs/3210434980/attempts/1) took nearly 3 hours but still didn't finish running, so I cancelled it. Is there any way to solve this 🤔 ?
<img width="1482" alt="Screenshot 2022-10-09 at 00 52 11" src="https://user-images.githubusercontent.com/97394017/194718762-b93289ae-1e64-4ba7-b528-6c58faa30371.png">
<img width="1109" alt="Screenshot 2022-10-09 at 00 55 52" src="https://user-images.githubusercontent.com/97394017/194718765-d75a3bdd-f375-47d9-9658-e9b0e62bde0b.png">

Since GUI tests are susceptible to OS-specific quirks, do we need to include GUI tests in tP? 

Also, do we have to resolve the failing codecov/patch check (#330) that is included in individual forked repo, or it's fine as long as the pull request passes all checks in the team repo? (The checks seem to be different in individual forked repo and team repo.)

**Comment by damithc** [comment]
If the test doesn't finish within 10 minutes or so, most likely it's stuck and best to cancel it rather than waste build minutes.

Does the test pass locally, on Linux?
If yes, you can insert extra print statements to see where the test get stuck during CI. Troubleshooting GUI test errors is hard (and take many trial-and-error attempts), especially so in CI environment (which doesn't have a display for you to see how the GUI tests executes).

**Comment by carriezhengjr** [comment]
> If the test doesn't finish within 10 minutes or so, most likely it's stuck and best to cancel it rather than waste build minutes.
> 
> Does the test pass locally, on Linux? If yes, you can insert extra print statements to see where the test get stuck during CI. Troubleshooting GUI test errors is hard (and take many trial-and-error attempts), especially so in CI environment (which doesn't have a display for you to see how the GUI tests executes).

Ok noted.

I'm using MacOS and the test can pass locally, not sure about Linux.
Do I have to use tools like Travis CI in order for build (ubuntu-latest) to pass?

**Comment by damithc** [comment]
> Do I have to use tools like Travis CI in order for build (ubuntu-latest) to pass?

@carriezhengjr AB4 uses Travis because GitHub actions did not exist at the time. Otherwise Travis plays the same role as GitHub Actions i.e., they are both CI platforms. That said, the Linux environment Travis provided back then might be different from the one GitHub actions provides now, which might make a difference for the tests. 

In fact, we switched the CS2103 tP from AB4 to AB3 sometime back because of this kind issues caused by GUI tests (at the time AB3 was basically AB4 minus GUI tests). 

If you eventually can't get it to work on Linux, you can skip those tests on Linux (GUI tests passing on 2/3 OS'es is better than nothing). Most importantly, given the time pressure of tP, don't let this issue affect your tP progress.

**Comment by carriezhengjr** [comment]
> > Do I have to use tools like Travis CI in order for build (ubuntu-latest) to pass?
> 
> @carriezhengjr AB4 uses Travis because GitHub actions did not exist at the time. Otherwise Travis plays the same role as GitHub Actions i.e., they are both CI platforms. That said, the Linux environment Travis provided back then might be different from the one GitHub actions provides now, which might make a difference for the tests.
> 
> In fact, we switched the CS2103 tP from AB4 to AB3 sometime back because of this kind issues caused by GUI tests (at the time AB3 was basically AB4 minus GUI tests).
> 
> If you eventually can't get it to work on Linux, you can skip those tests on Linux (GUI tests passing on 2/3 OS'es is better than nothing). Most importantly, given the time pressure of tP, don't let this issue affect your tP progress.

Yes, I also thought they are just tools for CI, but was not sure why the build could not be run successfully. 

Ok, thank you prof 😄 !
