### ISSUE TITLE
Error in Reading/Writing from Json File

### ISSUE THREAD

**Issue by johnrhimawan** [nus-cs2103-AY2223S1/forum#352]
```
Oct 19, 2022 12:16:43 AM seedu.intrack.MainApp init
INFO: =============================[ Initializing InTrack ]===========================
Oct 19, 2022 12:16:44 AM seedu.intrack.MainApp initConfig
INFO: Using config file : config.json
Oct 19, 2022 12:16:44 AM seedu.intrack.MainApp initPrefs
INFO: Using prefs file : preferences.json
Oct 19, 2022 12:16:44 AM seedu.intrack.commons.core.LogsCenter init
INFO: currentLogLevel: INFO
Oct 19, 2022 12:16:44 AM seedu.intrack.commons.util.JsonUtil readJsonFile
WARNING: Error reading from jsonFile file data\intrack.json: com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [simple type, class seedu.intrack.storage.JsonAdaptedTask] from String value ('Application submitted'); no single-String constructor/factory method
 at [Source: {
  "internships" : [ {
    "name" : "Test",
    "position" : "Software Engineer",
    "phone" : "324789",
    "email" : "test@test.com",
    "status" : "Progress",
    "address" : "hahaha",
    "taskFilled" : [ "Application submitted" ],
    "tagged" : [ ]
  } ]
}; line: 9, column: 22] (through reference chain: seedu.intrack.storage.JsonSerializableInTrack["internships"]->java.util.ArrayList[0]->seedu.intrack.storage.JsonAdaptedInternship["taskFilled"]->java.util.ArrayList[0])
Oct 19, 2022 12:16:44 AM seedu.intrack.MainApp initModelManager
WARNING: Data file not in the correct format. Will be starting with an empty InTrack
Oct 19, 2022 12:16:44 AM seedu.intrack.MainApp start
INFO: Starting InTrack V1.2.0ea
Oct 19, 2022 12:16:44 AM seedu.intrack.ui.UiManager start
INFO: Starting UI...
```

I encountered this error when launching my application. After going through the code, a ```DataConversionException``` is thrown. I think that there might be a problem with the reading/writing of the json file since after I enter the input, only the taskName of the ```Task``` class is stored in the json file (the ```Task``` class encapsulates both the taskName which is the description of the task and the taskTime which is the time the task is due).

**Comment by deeyonn** [comment]
Looking at the error and focusing on this portion,
`JsonMappingException: Can not instantiate value of type [simple type, class seedu.intrack.storage.JsonAdaptedTask] from String value ('Application submitted'); no single-String constructor/factory method`

and seeing that these are present,
`Data file not in the correct format.`
`"taskFilled" : [ "Application submitted" ],`

I'd infer that you're trying to parse an item of Task type rather than a JSON recognised type like a string.

I say this because you mentioned `only the taskName of the Task class is stored in the json file`.

You might need to explore how to "stringify" your Task onject before attempting to parse it.

I could be wrong but this is my best guess at it.

**Comment by johnrhimawan** [comment]
Thanks, already managed to solve this issue. My issue was that I override the toString() and getTask() methods in my ```JsonAdaptedTask``` class. This made the json file saved not in the manner it was supposed to.
