### ISSUE TITLE
Wrong spelling of 'microkernel'?

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2103-AY2223S1/forum#368]
In Design - Architecture - Styles video, is the word microkernel misspelt?

<img width="464" alt="image" src="https://user-images.githubusercontent.com/13196670/197373311-14986c02-ae22-4486-9e68-27b1e9fc3001.png">

As a side note, the explanation of service-oriented architecture styles is missing in the video even though it is a three-star topic in the textbook.

**Comment by damithc** [comment]
@cheeheng Yes, it should be microkernal
Yes, SOA may not be covered in the video -- videos don't cover all the topics. 
When and if I redo this video, I'll consider going into styles such as SoA some more.
In fact, the _Architectural Styles_ topic is one of the topics I've been meaning to expand on some more -- but it was not the top of my priority list because learning about architecture needs some SE experience first, and therefore, best done in second and subsequent SE modules such as CS3219.

**Comment by cheeheng** [comment]
> @cheeheng Yes, it should be ~~microkernal~~ (EDIT: microkernel)

Does it mean that the original spelling is correct?

Thanks so much for the clarification about the omission of SoA architecture.

**Comment by damithc** [comment]
> > @cheeheng Yes, it should be microkernal
> 
> Does it mean that the original spelling is correct?

Sorry, typo'ed again. Should me microkernel

**Comment by cheeheng** [comment]
Thanks so much prof!
