### ISSUE TITLE
Questions regarding correcting major flaws/bugs in Ui for 1.4

### ISSUE THREAD

**Issue by asaierika** [nus-cs2103-AY2223S1/forum#390]
Specifically, there are a few things in Ui that I believe would affect the functioning of the application.
1. The Ui components do not resize when the user enters fullscreen. This should be a behaviour that a user expects when entering the fullscreen as if the components do not resize automatically, the fullscreen would be quite useless. Thus, as we are allowing the user to enter the fullscreen, I think it should be expected that the components should resize. I am wondering if we are able to correct this in 1.4.
<img width="951" alt="Screenshot 2022-10-29 at 2 32 05 PM" src="https://user-images.githubusercontent.com/97216090/198817529-0ba4f6f2-4c2c-4ba3-85d2-114a8f5bddcb.png">
<img width="1280" alt="Screenshot 2022-10-29 at 2 32 11 PM" src="https://user-images.githubusercontent.com/97216090/198817532-7a25979e-a4df-4bfe-819c-e1bccf761654.png">

2. The help window text is editable. The user can delete and edit the text in the help window and this should not happen in any case for a real product. So may I know if this is considered a bug and can be corrected in 1.4?
<img width="728" alt="Screenshot 2022-10-29 at 2 37 30 PM" src="https://user-images.githubusercontent.com/97216090/198817727-ce6703fc-9bfc-4c6c-801f-f3a6bc1a3d32.png">
<img width="733" alt="Screenshot 2022-10-29 at 2 37 34 PM" src="https://user-images.githubusercontent.com/97216090/198817733-902d71cf-49c5-4e27-be65-0d0cef4cfa65.png">

3. Ui is not updated when user edits the details. The current Ui displaying a certain information of an entity is not updated when the user edits a certain detail, which only updates when the user triggers it by clicking the entity. May I know if this is considered a bug and can be fixed in 1.4?

4. Long names are cut off in Ui. May I know if I am able to modify the Ui to add new lines for the name, or modify the command to not allow names longer than a certain length?
<img width="732" alt="Screenshot 2022-10-29 at 2 34 33 PM" src="https://user-images.githubusercontent.com/97216090/198817869-3f89a304-bdcf-4609-9910-5a97b893ebcb.png">

5. Long tags can exceed the boundary of the panel. Similarly, may I know if I can correct this by limiting the length of the input tag?
<img width="394" alt="Screenshot 2022-10-29 at 2 41 24 PM" src="https://user-images.githubusercontent.com/97216090/198817921-97c4bb57-834c-46c7-aee9-a5f3ecca5bb6.png">

These are the bugs/flaws that I would want to change in 1.4 and it is ambiguous just by referring to the project requirements. So may I clarify here for each of them if I can correct them in 1.4?

**Comment by damithc** [comment]
@asaierika my answers below:

> 1. The Ui components do not resize when the user enters fullscreen. This should be a behaviour that a user expects when entering the fullscreen as if the components do not resize automatically, the fullscreen would be quite useless. Thus, as we are allowing the user to enter the fullscreen, I think it should be expected that the components should resize. I am wondering if we are able to correct this in 1.4.
> 
> <img alt="Screenshot 2022-10-29 at 2 32 05 PM" width="951" src="https://user-images.githubusercontent.com/97216090/198817529-0ba4f6f2-4c2c-4ba3-85d2-114a8f5bddcb.png">
> 
> <img alt="Screenshot 2022-10-29 at 2 32 11 PM" width="1280" src="https://user-images.githubusercontent.com/97216090/198817532-7a25979e-a4df-4bfe-819c-e1bccf761654.png">

If the resizing was implemented but was not working correctly due to a bug, you can fix it. But if it wasn't implemented at all in v1.3, the following applies.
![image](https://user-images.githubusercontent.com/1673303/198820291-4f8e54a2-f270-45a8-ba51-92a2f09a5385.png)


> 2. The help window text is editable. The user can delete and edit the text in the help window and this should not happen in any case for a real product. So may I know if this is considered a bug and can be corrected in 1.4?
> 
> <img alt="Screenshot 2022-10-29 at 2 37 30 PM" width="728" src="https://user-images.githubusercontent.com/97216090/198817727-ce6703fc-9bfc-4c6c-801f-f3a6bc1a3d32.png">
> 
> <img alt="Screenshot 2022-10-29 at 2 37 34 PM" width="733" src="https://user-images.githubusercontent.com/97216090/198817733-902d71cf-49c5-4e27-be65-0d0cef4cfa65.png">
> 

If you can show that it was caused by a bug in the code (e.g., the wrong UI component was used), you can fix it.

> 3. Ui is not updated when user edits the details. The current Ui displaying a certain information of an entity is not updated when the user edits a certain detail, which only updates when the user triggers it by clicking the entity. May I know if this is considered a bug and can be fixed in 1.4?

Yes, this sounds like a bug, assuming this result in the UI showing incorrect information to the user.

> 4. Long names are cut off in Ui. May I know if I am able to modify the Ui to add new lines for the name, or modify the command to not allow names longer than a certain length?
> 
> <img alt="Screenshot 2022-10-29 at 2 34 33 PM" width="732" src="https://user-images.githubusercontent.com/97216090/198817869-3f89a304-bdcf-4609-9910-5a97b893ebcb.png">
> 

~~Only if the current behavior results in an incorrect operation, such as wrong data being saved. Otherwise it would be fine-tuning a behavior, which is not allowed.~~ This can be fixed if it hinders users in their normal usage.
Also, it is fine not to optimize for user inputs that you don't expect in normal usage.  Users need to accept that the UI behavior may not be optimal for 'extreme' inputs. Hypothetically, catering for such extreme inputs can be postponed for a future version (beyond v1.4).

> 5. Long tags can exceed the boundary of the panel. Similarly, may I know if I can correct this by limiting the length of the input tag?
> 
> <img alt="Screenshot 2022-10-29 at 2 41 24 PM" width="394" src="https://user-images.githubusercontent.com/97216090/198817921-97c4bb57-834c-46c7-aee9-a5f3ecca5bb6.png">
> 

same as 4

**Comment by asaierika** [comment]
> 

Thank you for your reply! That answers my question :)

**Comment by damithc** [comment]
@asaierika please note the following edit.

> 4\. Long names are cut off in Ui. May I know if I am able to modify the Ui to add new lines for the name, or modify the command to not allow names longer than a certain length?
> 
> <img alt="Screenshot 2022-10-29 at 2 34 33 PM" width="732" src="https://user-images.githubusercontent.com/97216090/198817869-3f89a304-bdcf-4609-9910-5a97b893ebcb.png">
 
~Only if the current behavior results in an incorrect operation, such as wrong data being saved. Otherwise it would be fine-tuning a behavior, which is not allowed.~ This can be fixed if it hinders users in their normal usage i.e., not showing the full text can be considered an incorrect behavior (i.e., a bug).
