### ISSUE TITLE
Dropping (half) a feature 

### ISSUE THREAD

**Issue by nseah21** [nus-cs2103-AY2223S1/forum#401]
After last week's PE-D, my team has received feedback that two of our commands appear to be duplicate features with only minor differences between them. To elaborate:

1. `Command A` "overloads" the list command, which allows for users to include or exclude columns from the UI table when listing. It always causes the full list of persons to be displayed, resetting any effects of filter or find. 
2. `Command B` only allows users to hide columns from the UI table without affecting the residents listed. In addition, `Command B` can only be invoked on columns currently present in the UI table, while `Command A` does not have such a restriction. 

Some of the feedback received during PE-D was that the minute specification differences in both commands could be confusing, especially when users could easily chain `Command B` (vanilla column hiding) with other commands to achieve the same outcome. My team is currently leaning towards dropping `Command A`, i.e. the "overloaded" extension of the list command. 

Is it recommended to drop the feature provided by `Command A`, because its value-add can be obtained via chaining commands? 
Is there any reason ***not*** to drop a feature in v1.4?

We would appreciate any advice from @damithc, or any of the other tutors. Thank you.

**Comment by nealetham** [comment]
Hi all, I'm from the same group as @nseah21. To provide more context, `Command A` was implemented prior to `Command B` i.e. they were not done in parallel.

It was only after the implementation of `Command A`, did we see the value in implementing `Command B`, which was similar to `Command A` in functionality, but provided much better convenience and use cases for the user. As such, we could argue that `Command A` was the precursor to `Command B`.

Though they are not exactly the same feature, both achieve similar outcomes, with only minor differences as mentioned by @nseah21. We initially kept both of them as we felt that users could benefit from having both commands. However, seeing as it has caused confusion among our PE testers, we are now unsure if giving the user the option of having both commands, outweigh the value-add of having only a single "more powerful" `Command B`.

This brings in another interesting topic that is, in software design, is giving the user more options to perform the same tasks better? Or is it better to limit them to prevent confusion.

**Comment by damithc** [comment]
> This brings in another interesting topic that is, in software design, is giving the user more options to perform the same tasks better? Or is it better to limit them to prevent confusion.

This is a tough question to answer. Depends on the type of users as well. The opinion is divided. For example, Android follows the former while iOS (and Apple in general) follows the latter, and both have strong fan bases.

----

Back to the original question, you are certainly welcome to drop a feature but the decision is with you. Think from the target users' POV and see if at least _some_ of them will benefit from having both options. If yes, see if you can provide the additional option for those users without confusing the rest. For example, you can pitch the simpler version of the command as the main feature and mention the other version as an advanced shortcut, clearly stating what's the additional value at the start itself (so that users not interested in that benefit can skip the feature altogether).

Some points that may be relevant:

* If the command is expected to be used often, even saving one key stroke (e.g., giving a shorter alias) might save time for the user over the long time.
* Consider the maintenance cost of the feature. How much extra code does it need. Keep in mind that more code means more room for bugs.

**Comment by nseah21** [comment]
Thank you.
