### ISSUE TITLE
Clarification on how to qualify the boundaries of behavior that differs from the user guide (Input validation)

### ISSUE THREAD

**Issue by Ssatu** [nus-cs2103-AY2223S1/forum#408]
One of our testers for PE-D reported a bug regarding input restrictions which brought up a concern: **What qualifies as “Behavior that differs from the User Guide.”?**

![image](https://user-images.githubusercontent.com/69383469/199173555-1a0261f7-5797-4d8d-8300-dbd2a4d6b801.png)

For example, when handling input for positive integers, we specify in our user guide:
  
![image](https://user-images.githubusercontent.com/69383469/199172601-9c317271-6811-4ade-9450-3000f2678335.png)

In this case, the tester tried the input `+1` which was **rejected** as our code only allows nonzero unsigned integers.
Furthermore, a positive example was given "1, 2, 3 ... " (although _negative_ examples were not), does this still qualify as a positive integer (i.e. behavior in line with the user guide)

We could easily solve this by changing the restrictions to be "unsigned, nonzero integer" but we believe that affects readability for our users. Similarly, we could also specify that inputs with a positive sign e.g. "+1" is not allowed - strictly specifying the negative cases.

However, we think that there is value in clarifying the degree to which a user can interpret instructions - especially given positive examples! 

(Rather than trying to create a patchwork of constraints to cover loopholes. Some perhaps more extreme interpretations than `+1` might be inputting the string `"a positive integer"` for example. Other, different kinds of inputs can be similarly exploited in this manner.)

**Comment by damithc** [comment]
@Ssatu Based on the app domain, the command in concern, and the UG, is there any possibility that a user will think `+1` is expected instead of `1` when reading the UG? If the answer is 'no', then it should be fine as is.

You may tweak the UG further to improve clarity, if necessary. Yes, trying to make the explanation VERY precise can make the text hard to follow and less reader-friendly. One option is to provide additional constraints separately as 'small print', without obstructing the main flow of the explanation.
