### ISSUE TITLE
JavaDoc comments 

### ISSUE THREAD

**Issue by malwaregarry** [nus-cs2103-AY2223S1/forum#44]
Hi, would like to ask if JavaDoc comments for methods should be written before or after decorators:

Before
```java
/**
* Displays exit message.
*/
@Override
public void execute() {
```
After
```java
@Override
/**
* Displays exit message.
*/
public void execute() {
```

Which is correct / better? 

Thanks in advance!

**Comment by sltsheryl** [comment]
Hi there're a few examples here which said that it's usually placed before 
https://stackoverflow.com/questions/3109950/codestyle-put-javadoc-before-or-after-annotation

**Comment by clarence-chew** [comment]
The style guide references the [Google Java style guide](https://google.github.io/styleguide/javaguide.html).

In particular, the [Exception: Overrides](https://google.github.io/styleguide/javaguide.html#s7.3.2-javadoc-exception-overrides) section says "Javadoc is not always present on a method that overrides a supertype method.". It appears to conflict with "Write descriptive header comments for all public classes/methods." in our [style guide](https://se-education.org/guides/conventions/java/index.html). Since the supertype Javadoc can be consulted, I don't think we need to write it.

That aside, there may be a need to write it if the method is different from the supertype method.

[StackOverflow](https://stackoverflow.com/questions/3109950/codestyle-put-javadoc-before-or-after-annotation) here (as @sltsheryl just mentioned)
Summary: Java annotations is part of the code so the Javadoc is placed before the annotations.

**Comment by damithc** [comment]
> In particular, the [Exception: Overrides](https://google.github.io/styleguide/javaguide.html#s7.3.2-javadoc-exception-overrides) section says "Javadoc is not always present on a method that overrides a supertype method.". It appears to conflict with "Write descriptive header comments for all public classes/methods." in our [style guide](https://se-education.org/guides/conventions/java/index.html). Since the supertype Javadoc can be consulted, I don't think we need to write it.

Instead of repeating the same comment in the overridden method, you can use the following:
```java
/**
 * {@inheritDoc}
 */
```
You can also use it to add more explanations to the inherited javadoc, in case the child class behavior differs from the parent:
```java
/**
 * {@inheritDoc}
 * Some more explanations ...
 */
```

**Comment by damithc** [comment]
Update: I've tweaked our Java coding standard to allow omitting Javadoc comments for methods overriding a parent class method (conditions apply). See https://se-education.org/guides/conventions/java/intermediate.html#comments
