### ISSUE TITLE
Query about whether "Functionality Bug: Data not saved when more than one window is open #4146" is valid

### ISSUE THREAD

**Issue by sharmaine1028** [nus-cs2103-AY2223S1/forum#442]
# Bug reported
![image](https://user-images.githubusercontent.com/54767477/201458494-3a582b81-8ffb-4837-892a-7b951c78a3b1.png)
![image](https://user-images.githubusercontent.com/54767477/201458503-06e65a2f-1bf0-49b7-a50d-f1b403a50886.png)

# Why we think this bug is not in scope
We feel that the behaviour of our app is very reasonable. For instance, when we open multiple documents, it is true and expected that the app will take the latest one as the final changes. In addition, it is very rare for users to open the app twice.

Also, we feel that this bug would apply to almost all tP projects and getting penalised for a bug like this would be a little unfair. 

# Conclusion
Hence, we feel that this bug should not be not in scope.

Yet, we would like to check with the teaching team if our conclusion is valid.

**Comment by damithc** [comment]
@sharmaine1028  Does AB3 also have a similar behavior? ~~I don't remember that being the case.~~ (edit: perhaps that's case in AB3 as well; just want to confirm).

**Comment by sharmaine1028** [comment]
Hi Prof Damith, I have just tested it, and AB3 behaves the same way in that it takes the changes from the latest closed window. 

For instance 
1. Open two windows of AB3
2. In first window, enter `add n/John p/123 e/john@gmail.com a/NUS`
3. In second window, enter `add n/Ken p/123 e/ken@gmail.com a/NUS`
4. Exit both windows
5. AB3 takes changes from latest changed window

**Comment by damithc** [comment]
> Hi Prof Damith, I have just tested it, and AB3 behaves the same way in that it takes the changes from the latest closed window.

I see, in that case it becomes easier to argue for 'not in scope' (i.e., you didn't break something that worked already). Still, it depends on the application as 'not in scope' means the cost-benefit value of the features you've implemented already are higher than this feature.  So, it's still up to you to justify, based on the potential damage caused by this 'bug', how often it can happen, the effort required to fix it, etc. 
An alternative is to accept it as a documentation bug (if this limitation is not mentioned in the UG).

**Comment by sharmaine1028** [comment]
Okay thank you so much Prof Damith!
