### ISSUE TITLE
Clarification on disagreement criteria

### ISSUE THREAD

**Issue by ConradLew** [nus-cs2103-AY2223S1/forum#468]
In the following scenarios, are there sufficient grounds for disagreement?

1. The team downgrades the severity but does not provide any explanation. Does the FAQ mentioned in the website apply to the downgrading of severity as well instead of only outright rejections?

![image](https://user-images.githubusercontent.com/97608304/201881435-53abb8fa-2731-45b9-bb26-ba7d0d3a604e.png)

2. The team has claimed that the proposed feature flaw is not in scope, however, I am unsure about whether the feature flaw meets the criteria for "without much additional effort" as claimed by the website as fixing the flaw involves only about one or two lines of change for about 2 to 3 files. My concern is that there is no given benchmark to gauge this additional effort, and what can seem trivial and easy to implement for some might differ between people.

![image](https://user-images.githubusercontent.com/97608304/201884503-2c741b55-15ef-47a6-bea4-382336a41953.png)

**Comment by damithc** [comment]
@ConradLew 
1. Yes, you can disagree with it, and state that the team did not provide any explanation. To be safe, you can also state why you think your original severity is correct. But if you think the team's choice is correct in hindsight, it's best to agree with it though, as our primary goal is to find the correct characterization of the bug.
2. Yes, this is a judgement call. You can provide your justification (e.g., if the team has implemented much less useful features, why you think the feature flaw in concern is worth fixing compared to those less useful features, why you think it is easy to fix etc.). Without a strong justification, the teaching team is likely to side with NotInScope, as there are so many things one can add to the tP but there is very little time to do so. A NotInScope decision acknowledges that the issue is valid (and gives the tester a small reward for reporting it) without penalizing the dev team.

**Comment by ConradLew** [comment]
Noted, thanks prof!
