### ISSUE TITLE
Question regarding practice exam part 2/3 (Composition vs Aggregation)

### ISSUE THREAD

**Issue by Nephelite** [nus-cs2103-AY2223S1/forum#483]
In the part 2 sample answer/part 3, the relation used between activities was a composition relation, but I personally interpreted the relationship to not be a composition because of the following reasons:

1) I don't think that deleting the main activity would necessarily delete all connected activities since you could do sub-activities without the need for a main activity. E.g: "Having fun" has a sub-activity "Play piano", but deleting the "Having fun" activity may not result in the deletion of the "Play piano" sub-activity. Perhaps at some point, the user no longer finds the piano fun, but still does it because it's their job.

2) "Play piano" could also exist as an activity by itself without the need of a "Having fun" activity.

Should the relation then be aggregation instead, or is my logic wrong here, or am I overthinking this?

**Comment by Nephelite** [comment]
In addition, assuming i.e means 'for example', then sub-activity can just be an example of a relationship between activities, and not the only one. Then, suppose that an activity tracks 'alternative-activities' to do if the user does not want to do the activity in question. Clearly, this relationship can thus potentially be cyclic, which directly contradicts the usage case of compositions in this module.

**Comment by Devanshshah1309** [comment]
Hmm interesting interpretation. 

In my opinion, a "sub-activity" is a direct **part** of a bigger activity. The examples you mentioned make sense from a use-case POV but they aren't exactly "sub-activities" (e.g playing piano isn't a sub-activity of "having fun"). 

So, I think it is composition because of the hint given by the naming of the association itself (i.e., **sub-activity**). It's quite similar to: tasks and sub-tasks

An example of an activity and its sub-activity can be something like: 
Activity: Prepare for CS2103T Finals
Sub-activities:
1. Read textbook
2. Practice quizzes

Then, it becomes that there is a whole-part relationship between the activity and sub-activities right?

**Comment by Nephelite** [comment]
@Devanshshah1309 I see, that is probably the intent of the question then. Thanks!

**Comment by damithc** [comment]
Good answer @Devanshshah1309 Yes, that was the intention of the question.
