### ISSUE TITLE
Follow-up questions not being submitted

### ISSUE THREAD

**Issue by Devanshshah1309** [nus-cs2103-AY2223S1/forum#492]
Hi Prof, I followed the instructions on how to submit the follow-up questions on Examplify and even checked the Request Feedback option before moving to the next question for the practice exam. 

However, I got an email saying that those answers were not submitted.

Could you please clarify if there's anything I missed out?

(Is anyone else facing the same issue?)

**Comment by danielk0k** [comment]
Same here, was going to submit an issue as well.

**Comment by yuanxi1** [comment]
Same but I only did the 2 practice paper instead of the mock. Might be because the teaching team only checked the mock paper instead of the practice paper.

**Comment by danielk0k** [comment]
<img width="1512" alt="Screenshot 2022-11-24 at 1 41 38 PM" src="https://user-images.githubusercontent.com/70556073/203704125-d1291375-7407-4fcb-b567-edbf45055382.png">

I get this double tick boxes whenever I select the "Request Feedback" box. Not sure if that's the reason...

**Comment by Devanshshah1309** [comment]
Yeah same but the top one disappears after a second or so right? Seems like a glitch to me

**Comment by damithc** [comment]
Guys, Our initial check was on the mock exam paper only (the one with only 3 questions), not the practice exam papers. Since then, we also checked practice exam part 1 submissions and sent a second email if we were able to find your follow-up answers in there (the second email was sent to only those who didn't have follow-up responses in the first check).
