### ISSUE TITLE
Module's policy on code / documentation written by GitHub Copilot

### ISSUE THREAD

**Issue by RezwanArefin01** [nus-cs2103-AY2223S1/forum#51]
What is this module's policy on code written by GitHub Copilot? Since there are a lot of public repository implementing this project, copilot will almost be copying code from them. The current code reuse policy for external sources says: 

> You clearly give credit to the original author. Acknowledge use of third party resources clearly e.g. in the welcome message, splash screen (if any) or under the 'about' menu. If you are open about reuse, you are less likely to get into trouble if you unintentionally reused something copyrighted.

In case of Copilot, it would be almost impossible to give credit. ~~Should I write `@@author GitHub Copilot`?~~

Also the javadoc generated by Copilot is almost accurate. Multiple students using Copilot to write javadocs may result in incorrect plagiarism verdict.

**Comment by nehcuy** [comment]
I guess turning it off makes more sense since it would essentially be blatant plagiarism. 😱

**Comment by damithc** [comment]
Good question @RezwanArefin01 
While we do not prohibit use of Copilot (such a policy would be hard to enforce anyway), we will not accept "it was generated by co-pilot" as justification for plagiarism. 
On a related note, I expect at least some companies to prohibit their devs from using copilot due to possible plagiarism or licensing pitfalls.

**Comment by deeyonn** [comment]
I thought copilot only helps by suggesting very common boilerplate code that is often reused over and over again.

**Comment by RezwanArefin01** [comment]
@deeyonn Try it for some time. You'll find out what it is capable of.
