### ISSUE TITLE
After merging, why my Sourcetree only showed master branch when pushing?

### ISSUE THREAD

**Issue by bokun2** [nus-cs2103-AY2223S1/forum#52]
After merging level 7 into master, it is required that we push both master and branch-level-7 , however when I tried to push, on the "branch to push" template, the only choice is "master" and no branch-level-7. Is it because the version of the Sourcetree? Or is it because I have pushed branch-level-7 before merging?...Can I just push it like this? Also, is there someway to check whether or not my push is right? Thank you for helping

**Comment by damithc** [comment]
@bokun2 it might help if you share relevant screenshots

**Comment by bokun2** [comment]
![image](https://user-images.githubusercontent.com/97288772/186077701-7b72e50b-c8f3-40f1-b592-ec0c29153120.png)
![image](https://user-images.githubusercontent.com/97288772/186077736-a7c97570-d822-4030-884c-72ab9e3f456b.png)
can this work?

**Comment by hauchongtang** [comment]
Looks like you have merged L-7 branch with master. To update the remote repo, you just need to push ^ to your fork. After which, your fork should have the commit "Merge branch-Level-7 ... ... ". (Check ur fork repo on github)

**Comment by bokun2** [comment]
Oh I think I have misunderstood what the project said...Thank you for your help. I will try it

**Comment by damithc** [comment]
@bokun2 we require you to push both the master branch and the other branches. Pushing the `master` branch doesn't automatically push the other branched merged to it. However, you seem to have pushed `branch-Level-7` already. As per below, your local branch and the corresponding remote branch are pointing to the same commit (i.e., the remote branch is in sync with the local branch)
![image](https://user-images.githubusercontent.com/1673303/186082911-7453a2bb-b3e6-490a-a764-ed3483e0d638.png)

But your local master branch is two commits ahead of the remote master branch. That means you need to push it.
![image](https://user-images.githubusercontent.com/1673303/186083541-852bd503-0e32-4e18-8345-cee7bcfb2f1c.png)

I've marked the two commits in concern. Yes, commit `1` is part of `master` branch as well (due to the merge).

**Comment by bokun2** [comment]
So this is the reason why I can only choose to push the master branch? Thank you for your clarification, prof.
