### ISSUE TITLE
A-Gradle

### ISSUE THREAD

**Issue by adeearyaa** [nus-cs2103-AY2223S1/forum#55]
Hi I just wanted to check how do we merge the gradle branch with our main branch because even after I have forked the ip repo it only copied over the original branch not the add-gradle branch or is there something else we have to do?

**Comment by leonidas1712** [comment]
You could try pulling the branch into a local branch on your repo using the answer from [here](https://stackoverflow.com/questions/5884784/how-to-pull-remote-branch-from-somebody-elses-repo) (user Antak's answer).

So you would execute this in your command line (after changing to the ip directory) to get the add-gradle-support branch from the original repo into a local branch with the same name, then merge the changes from the branch into your own branch:
`git fetch git@github.com:nus-cs2103-AY2223S1/ip.git add-gradle-support:add-gradle-support`
`git switch master`
`git merge add-gradle-support`

(assuming you want to merge the changes into your master branch - otherwise replace master with the name of the branch you want to merge into)

Just tried it and didn't seem to have any merge conflicts. Does this help?

**Comment by Hikoya** [comment]
Either that or you can simply do a 

`git merge --no-ff upstream/add-gradle-support`

See if it helps you merge the gradle branch to your master.

EDIT: Check whether you have the upstream repo set by running `git remote -v`

![image](https://user-images.githubusercontent.com/13346668/186162018-dadcb123-614e-4e90-89b6-cecee7c6e730.png)

Else simply do a `git remote add upstream git@github.com:nus-cs2103-AY2021S1/ip.git` and run the merge command again

**Comment by bokun2** [comment]
You could try to add the nus-cs2103-AY2223s1 as a remote repo and try to pull the add-cradle branch to your master branch. This can only copy add-gradle branch to your master branch.

**Comment by johnbenedictyan** [comment]
Hi @Hikoya thanks for the answer, I ran into some errors just using the git merge command but I managed to find a workaround and I'll share it with other users.

1. `git remote add upstream https://github.com/nus-cs2103-AY2223S1/ip.git`
2. `git fetch upstream add-gradle-support`
3. `git merge upstream/add-gradle-support`

This is how I got it to work on my machine (M1 Mac), in case it's an OS thing.
