### ISSUE TITLE
Clarification on Week 1 Quiz Question 45

### ISSUE THREAD

**Issue by seanflyyy** [nus-cs2103-AY2223S1/forum#6]
Hello all! I was attempting the quiz and for this question, 

"It is redundant for a ‘try’ block to have a ‘finally’ block if you already have a ‘catch’ block."

I had selected true since according to the Week 1 Syllabus, "The try statement should contain at least one catch block or a finally block and may have multiple catch blocks." But the solution provided was True since "They have different purposes." 

Just wanted to clarify on this because it was a bit confusing for me, because technically, it is redundant for a ‘try’ block to have a ‘finally’ block if you already have a ‘catch’ block since you should have either at least one catch block or a finally block, just that they have different purposes so in practice, they are not exclusive(?)

**Comment by e1010101** [comment]
From my understanding, a "finally" block always runs regardless of whether an exception occurs. Quoting from [this post](https://stackoverflow.com/questions/1158667/why-use-finally-in-try-catch) on StackOverflow: 

_"...Finally will always run (barring program crash). If the function exits inside of the try catch block, or another error is thrown in either the try or the catch, the finally will still execute. You won't get that functionality not using the finally statement."_

Here's an example from [Oracle Docs](https://docs.oracle.com/javase/tutorial/essential/exceptions/finally.html) where "finally" is used to perform cleanup (which you want to do regardless of an exception occurring or not):

```
finally {
    if (out != null) { 
        System.out.println("Closing PrintWriter");
        out.close(); 
    } else { 
        System.out.println("PrintWriter not open");
    } 
    if (f != null) {
	    System.out.println("Closing FileWriter");
	    f.close();
	}	
} 
```

So "catch" and "finally" have different purposes as code inside "catch" blocks are only executed when an exception occurs, while "finally" contains code that runs regardless of any exceptions. Note that putting the cleanup code outside a "finally" in the above example would result in the cleanup code not being executed since the program would terminate before.

Hope this helps!

**Comment by seanflyyy** [comment]
Thanks for the clarification! That does make sense haha. Perhaps the question could have been phrased better because it contradicts what it says in the textbook that a try block should have either at least one catch statement or a finally statement haha

**Comment by rylzxc** [comment]
I think the reason why we have a try-catch block in the first place is because we **expect** the program to throw errors, and we perform exception handling. So, what if we can't expect/predict an exception being thrown? As @e1010101 mentioned, the finally block contains code that runs **regardless of any exceptions thrown**, in this case it is useful if to have cleanup code in your finally block to do whatever cleanup required. Therefore, it is encouraged for a try block should have either at least one catch or finally to cover all bases.

**Comment by damithc** [comment]
> "The try statement should contain at least one catch block or a finally block and may have multiple catch blocks." 
>
> "It is redundant for a ‘try’ block to have a ‘finally’ block if you already have a ‘catch’ block."


@seanflyyy 
The first statement is about what is allowed by the syntax. _catch block **or** a finally block_ implies you are _allowed_ to omit the `finally` block when there there is a `catch` block.
The second sentence is about the usefulness of having a `finally` block when there is already a `catch` block i.e., does having a `catch` block negate the need for having a `finally` block? 

Now, keep in mind that the purpose of the program is not simply to follow syntax rules, although it is a necessity. Therefore, _allowed to omit_ does not mean _redundant_.
For example, a certain piece of code can be useless (i.e., redundant) but still allowed by the syntax. Conversely, the code can be useful although not strictly required by the syntax.
In this case, such a `finally` block can still serve a useful purpose although not strictly required by the syntax. But you can omit it too, for instance, if there is no need to run some clean up code (that's why the syntax allows omitting it).

**Comment by seanflyyy** [comment]
@damithc Thank you for your clarification prof! It is much clearer now.
