### ISSUE TITLE
Unable to commit on Sourcetree on a different laptop

### ISSUE THREAD

**Issue by guokweijie** [nus-cs2103-AY2223S1/forum#63]
hi everyone, i got this error when trying to make a commit on sourcetree and I am unable to make the commits.

git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks commit -q -F C:\Users\guokw\AppData\Local\Temp\vt5wabz0.avy
fatal: cannot update the ref 'HEAD': unable to append to '.git/logs/HEAD': Invalid argument
Completed with errors, see above.

does anyone happen to know what this means? I just downloaded Sourcetree, and downloaded Git on Intellij and made changes on my iP on a new laptop today, if it affects because its not the original device.

**Comment by guokweijie** [comment]
update: i cloned from my own iP repo onto my new device and copied over the changes i made and now i can commit. this is probably because of my change of device and transferring of files by onedrive?

**Comment by pyk595** [comment]
Hi @guokweijie, I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems).  As you suspected, it is probably because you transferred the files over to your new device using onedrive instead of Git. This causes the references to the remote repository to be corrupted, as seen in the error message `cannot update the ref 'HEAD'`. More details on the issue can be found [here](https://stackoverflow.com/a/69950854). The common practice for transferring files between devices would be to clone the remote repository directly, to avoid such issues. Hope this helps!

**Comment by domlimm** [comment]
Hello @guokweijie, like Yuan Ker above, I'm from your senior batch. Adding onto what Yuan Ker has said:

Cloning your own iP repo onto your new device should be fine. May I ask how did you copy the changes over?

For e.g., probably on your old device, you might have a text file, `Temp.txt`. If you saved this file onto OneDrive, downloaded it to your new device and copied it into the directory which you cloned your iP repo, it shouldn't be of any problem.

I think this issue that you previously faced comes only when you saved your iP repo from your old device, and then downloaded the folder to your new device. There is a hidden `.git` file (more on what this file contains [here](https://stackoverflow.com/questions/29217859/what-is-the-git-folder)) in your iP directory which contains information required for version control or any directory with a `.git` file for that matter, and copying the iP repo from OneDrive to your new device could have changed some of the paths/reference to `HEAD` stored in the `.git`.

Hope this was helpful! And glad that you solved your problem! 🍻

**Comment by guokweijie** [comment]
Thank you seniors! @domlimm @pyk595
