### ISSUE TITLE
Unable to refactor duke.java into duke package

### ISSUE THREAD

**Issue by bryanngzh** [nus-cs2103-AY2223S1/forum#66]
I'm currently doing A-Packages and I can't seem to refactor duke.java into the duke package.
I've created a package called duke under src/main/java. When i try to drag my duke.java from src/main/java to src/main/java/duke, this error message pops up.
<img width="967" alt="image" src="https://user-images.githubusercontent.com/50972999/186604620-9cb283d2-f220-4c32-bb7a-0cd0e44d019a.png">
Furthermore, I'm not able to run the code as I'm given this error. (If I try to force refactor duke.java into src/main/java/duke.)
<img width="483" alt="image" src="https://user-images.githubusercontent.com/50972999/186607142-06d98853-c1c8-457b-8e5c-51c76546beed.png">
I'm only able to run Duke.java if I move it back to src/main/java.
How do I make it such that I can move my duke.java into src/main/java/duke and make it still be able to run? 
Edit: I'm running this on MacOS Intel. 
Would appreciate any help, thanks!

**Comment by Echomo-Xinyu** [comment]
In this case, the default running command is still to run the `Duke.java` at the previous location and hence it cannot find the main class `Duke` as the file is no longer there. You need to edit the configuration by updating the path of `Duke.java` in order to accommodate the refactor.

Another simple way to fix is to click the green run button beside your current `Duke.java` `main` class and it will automatically form a new `Duke(1)` configuration to execute the file.

**Comment by bryanngzh** [comment]
@Echomo-Xinyu thank you! It works.
