### ISSUE TITLE
Adding local storage text file to gitignore

### ISSUE THREAD

**Issue by ConradLew** [nus-cs2103-AY2223S1/forum#70]
Am I allowed to add the file used to store tasks locally to .gitignore? Doing on-the-fly manual testing causes changes in the file that in turn sometimes forces me to make a redundant commit before checking out to other branches to do other levels/deliverables.

**Comment by teekaytai** [comment]
I don't see why not. It makes sense that the data file should not be committed.

Side note, regarding this part

> redundant commit before checking out to other branches

If I understand correctly you are making temporary commits so that you can clear the current changes and allow yourself to move to another branch?  
If so you could benefit from using the `git stash` command to temporarily shelve changes and move to something else. Here's the entry in the [textbook](https://nus-cs2103-ay2223s1.github.io/website/se-book-adapted/chapters/gitAndGithub.html#stash-shelving-changes-temporarily).
