### ISSUE TITLE
Storing start and end date time in `Event`

### ISSUE THREAD

**Issue by jasonqiu212** [nus-cs2103-AY2223S1/forum#82]
Hi everyone, 

For `Level-8`, I noticed that the instructions only mentioned to store **deadline** dates as a `java.time.LocalDateTime`. 

Should we implement the same feature to store date time for `Event` as well? And if so, would it be better to store both a start and end date time to indicate an interval? Could we add additional flags to the `event` command to input the start and end date times (eg. `/start` and `/end`)? 

Thanks!

**Comment by damithc** [comment]
@jasonqiu212 The iP requirements are flexible on this. You guys can discuss alternatives and choose something suitable.

**Comment by rylzxc** [comment]
You can follow the date format as you did to store deadline dates, and that's the minimal requirement if I'm not wrong.

Customisability of Duke is allowed hence addition of extra flags is permitted.

**Comment by sltsheryl** [comment]
Hi if you see under stretch goal, they included Event as well. It’s a good idea to be able to handle Event too because its arguments can be in the form of a standard date too.

As said by the rest, we have quite a lot of freedom to customise how we want to utilise the date time and how we take in inputs and outputs. 

I think the interval idea is nice because it gives us extra features eg. a deadline can have different starting time. Other extensions are handling different date formats. But it requires more work like how we split the string and additional things to keep track. But if it’s something that we want, we should go for it. To be safe, before doing extra, make sure our program can handle the minimum requirement ie. the example input yyyy-mm-dd.

**Comment by jasonqiu212** [comment]
Thank you everyone for your advice! Will consider adding an additional flag :)
