### ISSUE TITLE
A-OOP: Can we call TaskList functions within Parser class?

### ISSUE THREAD

**Issue by agarwal-anjali** [nus-cs2103-AY2223S1/forum#91]
As per the guidelines Parser class must interpret the user input. So after interpreting the user input can we perform the required actions on the list of tasks (using the functions of the TaskList class) within the Parser class itself or do we need to return the interpreted user input back to the Duke class and call TaskList functions there?

**Comment by damithc** [comment]
Good question @agarwal-anjali . Opinions invited on what pros and cons you guys see of these two (and any other) alternatives.

**Comment by sltsheryl** [comment]
I feel performing TaskList methods in the Parser class may not be that ideal because we would need to pass the list of tasks around which is quite clumsy . 

It may be better to have an abstract class Command (written in A-More-OOP) and in the Parser class, create instance of the different types of commands. And each command class handles adding or removing task from the task list. I find this more natural as the job of task management (adding and removing tasks) and parsing the input string are handled separately.
